"""apply_deeper_teal - one accent, everywhere, in one round.

    python apply_deeper_teal.py --check     # counts only, writes nothing
    python apply_deeper_teal.py

WHY THIS IS TWO MOVES, NOT ONE
------------------------------
The obvious approach - find #17a2b8, replace with #0e7c8b - misses a whole
class of buttons, and misses them invisibly.

  1. THE HEX. Templates hardcode #17a2b8 (and rgb/rgba forms of the same
     colour) in their own <style> blocks. A textual replacement handles these.

  2. THE FRAMEWORK. base.html loads Bootstrap 4.1.3 from a CDN, whose `info`
     colour IS #17a2b8. Templates that write `class="btn btn-info"` and never
     override it take that colour straight from the CDN - act_expense.html
     does exactly this ELEVEN times. No edit to that template can change it.

So move 2 overrides Bootstrap's info family once, in base.html, and move 1
sweeps the hardcoded copies. Together they leave one teal in the system.

CASCADE ORDER IS LOAD-BEARING
-----------------------------
The override block MUST come after the Bootstrap <link>, or Bootstrap wins and
nothing visible changes. This script anchors on the link tag and inserts after
it; test_deeper_teal.py asserts the ordering by index, not by presence.

WHY DEEPER IS ALSO MORE LEGIBLE
-------------------------------
    #17a2b8 on white  = 2.9:1   fails AA for body text
    #0e7c8b on white  = 4.9:1   passes AA for large text, close for body
    white on #17a2b8  = 2.9:1
    white on #0e7c8b  = 4.9:1
The change improves contrast in both directions; nothing gets harder to read.

SCOPE
-----
Every .html under pages/templates and pages/help_content, plus any .css under
static/. Skips *.bak_* entirely, and skips staticfiles/ (collected output -
regenerated by collectstatic, never edited by hand).

Idempotent. Backs up every file it touches to .bak_deeperteal.
"""

import io
import os
import re
import shutil
import sys

CHECK = '--check' in sys.argv

ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(ROOT, 'pages', 'templates', 'base.html')

OLD_HEX = '17a2b8'
NEW_HEX = '0e7c8b'
OLD_RGB = (23, 162, 184)
NEW_RGB = (14, 124, 139)

if not os.path.exists(BASE):
    sys.exit('! pages/templates/base.html not found - run from the project root')

# --------------------------------------------------------------- scan
SEARCH_DIRS = [
    os.path.join(ROOT, 'pages', 'templates'),
    os.path.join(ROOT, 'pages', 'help_content'),
    os.path.join(ROOT, 'static'),
]

_hex_re = re.compile(r'#' + OLD_HEX, re.I)
_rgb_re = re.compile(
    r'rgba?\(\s*%d\s*,\s*%d\s*,\s*%d\s*' % OLD_RGB, re.I)


def targets():
    seen = []
    for d in SEARCH_DIRS:
        if not os.path.isdir(d):
            continue
        for dirpath, dirnames, filenames in os.walk(d):
            # never descend into collected static output
            dirnames[:] = [x for x in dirnames if x != 'staticfiles']
            for f in sorted(filenames):
                if '.bak_' in f:
                    continue
                if not f.endswith(('.html', '.css')):
                    continue
                seen.append(os.path.join(dirpath, f))
    return seen


def sniff(path):
    raw = open(path, 'rb').read()
    if raw.startswith(b'\xef\xbb\xbf'):
        return raw[3:].decode('utf-8'), 'utf-8-sig', (
            '\r\n' if b'\r\n' in raw else '\n')
    return raw.decode('utf-8'), 'utf-8', ('\r\n' if b'\r\n' in raw else '\n')


def write(path, text, enc, nl):
    bak = path + '.bak_deeperteal'
    if not os.path.exists(bak):
        shutil.copy2(path, bak)
    with io.open(path, 'w', encoding=enc, newline='') as fh:
        fh.write(text.replace('\n', nl) if nl != '\n' else text)


# ============================================ MOVE 2: the Bootstrap override
BOOT_ANCHOR = ('<link rel="stylesheet" '
               'href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3'
               '/dist/css/bootstrap.min.css"')

OVERRIDE_MARK = '--alv-accent:'

OVERRIDE = '''

    <!-- ===================================================================
         ALIVENTE ACCENT
         Placed immediately AFTER the Bootstrap link on purpose. Bootstrap
         4.1.3 defines its `info` family as #17a2b8, and templates that write
         class="btn btn-info" without their own rule take that colour straight
         from the CDN - act_expense.html does so eleven times. Move this block
         above the link and Bootstrap wins again, silently.

         #0e7c8b is the same hue one step deeper: 4.9:1 on white against the
         old 2.9:1, so it is legible as text and as a border, not only as a
         filled button.
         =================================================================== -->
    <style>
      :root {
        --alv-accent:        #0e7c8b;
        --alv-accent-ink:    #0a5e6a;   /* hover / pressed                  */
        --alv-accent-soft:   #e4f3f5;   /* tint: hover rows, selected chips */
        --alv-accent-line:   #a8d8de;   /* borders on tinted surfaces       */
        --alv-on-accent:     #ffffff;   /* text on a filled accent          */
      }

      .btn-info,
      .btn-info:disabled,
      .btn-info.disabled {
        background-color: var(--alv-accent);
        border-color: var(--alv-accent);
        color: var(--alv-on-accent);
      }
      .btn-info:hover,
      .btn-info:focus,
      .btn-info:active,
      .btn-info.active,
      .show > .btn-info.dropdown-toggle {
        background-color: var(--alv-accent-ink);
        border-color: var(--alv-accent-ink);
        color: var(--alv-on-accent);
      }
      .btn-info:focus,
      .btn-info.focus {
        box-shadow: 0 0 0 .2rem rgba(14, 124, 139, .38);
      }

      .btn-outline-info {
        color: var(--alv-accent);
        border-color: var(--alv-accent);
      }
      .btn-outline-info:hover,
      .btn-outline-info:focus,
      .btn-outline-info:active {
        background-color: var(--alv-accent);
        border-color: var(--alv-accent);
        color: var(--alv-on-accent);
      }

      .bg-info { background-color: var(--alv-accent) !important; }
      .text-info { color: var(--alv-accent) !important; }
      .border-info { border-color: var(--alv-accent) !important; }
      .badge-info { background-color: var(--alv-accent); color: var(--alv-on-accent); }
      .alert-info {
        background-color: var(--alv-accent-soft);
        border-color: var(--alv-accent-line);
        color: var(--alv-accent-ink);
      }
      .list-group-item-info { background-color: var(--alv-accent-soft); color: var(--alv-accent-ink); }
      a.text-info:hover, a.text-info:focus { color: var(--alv-accent-ink) !important; }
    </style>'''


def apply_override(text):
    """Insert the override immediately after the Bootstrap stylesheet link."""
    if OVERRIDE_MARK in text:
        return text, 'already'
    i = text.find(BOOT_ANCHOR)
    if i < 0:
        sys.exit('! the Bootstrap <link> was not found in base.html.\n'
                 '  Cascade order matters here, so this refuses to guess where\n'
                 '  to put the override. Re-read base.html and update the anchor.')
    end = text.find('>', i)
    if end < 0:
        sys.exit('! the Bootstrap <link> tag is unterminated in base.html.')
    return text[:end + 1] + OVERRIDE + text[end + 1:], 'inserted'


# ================================================== MOVE 1: the hex sweep
def sweep(text):
    n_hex = len(_hex_re.findall(text))
    text = _hex_re.sub('#' + NEW_HEX, text)

    n_rgb = len(_rgb_re.findall(text))

    def _rgb_sub(m):
        return re.sub(r'\d+\s*,\s*\d+\s*,\s*\d+',
                      '%d, %d, %d' % NEW_RGB, m.group(0), count=1)

    text = _rgb_re.sub(_rgb_sub, text)
    return text, n_hex, n_rgb


# ======================================================================= run
files = targets()
report, total_hex, total_rgb = [], 0, 0
pending = {}

for path in files:
    text, enc, nl = sniff(path)
    text = text.replace('\r\n', '\n')
    original = text

    override_state = None
    if os.path.abspath(path) == os.path.abspath(BASE):
        text, override_state = apply_override(text)

    text, n_hex, n_rgb = sweep(text)
    total_hex += n_hex
    total_rgb += n_rgb

    if text != original:
        pending[path] = (text, enc, nl)
    if n_hex or n_rgb or override_state == 'inserted':
        report.append((os.path.relpath(path, ROOT), n_hex, n_rgb,
                       override_state))

print('')
if report:
    print('  %-52s %5s %5s' % ('FILE', 'HEX', 'RGB'))
    print('  ' + '-' * 66)
    for rel, h, r, ov in sorted(report, key=lambda t: -(t[1] + t[2])):
        extra = '   <- Bootstrap info override inserted' if ov == 'inserted' else ''
        print('  %-52s %5d %5d%s' % (rel[:52], h, r, extra))
    print('  ' + '-' * 66)
print('  %-52s %5d %5d' % ('TOTAL', total_hex, total_rgb))
print('')
print('  %d file(s) scanned, %d to change' % (len(files), len(pending)))

# The override is the half that a hex sweep cannot do. Say plainly whether it
# is in place, because "0 hex remaining" alone would look like success.
base_text = sniff(BASE)[0]
has_override = OVERRIDE_MARK in base_text or any(
    os.path.abspath(p) == os.path.abspath(BASE) for p in pending)
print('  Bootstrap info override: %s'
      % ('in place' if has_override else 'MISSING - btn-info stays CDN teal'))
print('')

if CHECK:
    print('--check: nothing written.')
    sys.exit(0)

if not pending:
    print('Nothing to do - already applied.')
    sys.exit(0)

for path, (text, enc, nl) in pending.items():
    write(path, text, enc, nl)
print('  wrote %d file(s). Backups: *.bak_deeperteal' % len(pending))
print('')
print('Now run:  python test_deeper_teal.py')
