#!/usr/bin/env python
"""
update_analysis_modal.py — replace the installed Expenses-vs-Rent Analysis
modal block in act_expense.html with the latest version (fits without
scrolling + labelled quadrants). The Analysis buttons are left untouched.

Run from the project root:

    python update_analysis_modal.py             # apply (backs up the template)
    python update_analysis_modal.py --dry-run   # preview only

Backs up the template to <file>.bak_analysis_update once. Safe to re-run.
"""
import base64, os, sys

DRY = '--dry-run' in sys.argv

NEW_BLOCK = base64.b64decode("".join([
    "PCEtLSA9PT09PT09PT09PT09PT09PT09PSBFWFBFTlNFUyB2cyBSRU5UIOKAlCBBTkFMWVNJUyBNT0RBTCA9PT09PT09PT09PT09"
    "PT09PT09PSAtLT4KPHN0eWxlPgouYW5hbHlzaXMtZGlhbG9nIHsgbWF4LXdpZHRoOiA5MjBweDsgfQouYW5hbHlzaXMtZGlhbG9n"
    "IC5tb2RhbC1ib2R5IHsgbWF4LWhlaWdodDogODJ2aDsgb3ZlcmZsb3cteTogYXV0bzsgfQouYW5hbHlzaXMtc3ViIHsgY29sb3I6"
    "IzZjNzU3ZDsgZm9udC1zaXplOjEyLjVweDsgbWFyZ2luOiA0cHggMCAxMHB4OyB9Ci5hbmFseXNpcy1jaGFydC13cmFwIHsgcG9z"
    "aXRpb246IHJlbGF0aXZlOyB3aWR0aDogMTAwJTsgaGVpZ2h0OiA0MHZoOyBtaW4taGVpZ2h0OiAyNjBweDsgbWF4LWhlaWdodDog"
    "NDAwcHg7IG1hcmdpbi1ib3R0b206IDEwcHg7IH0KLmFuYWx5c2lzLXF1YWQta2V5IHsgZGlzcGxheTpncmlkOyBncmlkLXRlbXBs"
    "YXRlLWNvbHVtbnM6MWZyIDFmcjsgZ2FwOjVweCAxNnB4OyBtYXJnaW46MCAwIDE0cHg7IGZvbnQtc2l6ZToxMS41cHg7IGNvbG9y"
    "OiM0OTUwNTc7IH0KLmFuYWx5c2lzLXF1YWQta2V5IC5xayB7IGxpbmUtaGVpZ2h0OjEuMzU7IH0KLmFuYWx5c2lzLXF1YWQta2V5"
    "IC5xayBiIHsgZGlzcGxheTpibG9jazsgfQouYW5hbHlzaXMtcXVhZC1rZXkgLnFrLmRhbmdlciBiIHsgY29sb3I6I2IwMmEzNzsg"
    "fQouYW5hbHlzaXMtcXVhZC1rZXkgLnFrLmdvb2QgYiB7IGNvbG9yOiMxZjdhMzc7IH0KLmFuYWx5c2lzLXRhYmxlIHRib2R5IHRy"
    "LmRhbmdlci1yb3cgeyBiYWNrZ3JvdW5kOiNmZGVjZWM7IH0KLmFuYWx5c2lzLXRhYmxlIHRkLm51bSwgLmFuYWx5c2lzLXRhYmxl"
    "IHRoLm51bSB7IHRleHQtYWxpZ246cmlnaHQ7IGZvbnQtdmFyaWFudC1udW1lcmljOiB0YWJ1bGFyLW51bXM7IH0KLmFuYWx5c2lz"
    "LWZsYWcgeyBmb250LXNpemU6MTFweDsgZm9udC13ZWlnaHQ6NzAwOyBwYWRkaW5nOjJweCA4cHg7IGJvcmRlci1yYWRpdXM6MjBw"
    "eDsgfQouYW5hbHlzaXMtZmxhZy53YXJuIHsgYmFja2dyb3VuZDojZmRlY2VjOyBjb2xvcjojYzAzMjJmOyB9Ci5hbmFseXNpcy1m"
    "bGFnLm9rIHsgYmFja2dyb3VuZDojZThmNmVjOyBjb2xvcjojMWY3YTM3OyB9Ci5hbmFseXNpcy1zcmMgeyBmb250LXNpemU6MTFw"
    "eDsgY29sb3I6I2FkYjViZDsgfQpAbWVkaWEgKG1heC13aWR0aDogNzY4cHgpIHsKICAuYW5hbHlzaXMtZGlhbG9nIHsgbWF4LXdp"
    "ZHRoOjEwMCU7IG1hcmdpbjowOyBoZWlnaHQ6MTAwdmg7IH0KICAuYW5hbHlzaXMtZGlhbG9nIC5tb2RhbC1jb250ZW50IHsgaGVp"
    "Z2h0OjEwMHZoOyBib3JkZXItcmFkaXVzOjA7IGJvcmRlcjpub25lOyBkaXNwbGF5OmZsZXg7IGZsZXgtZGlyZWN0aW9uOmNvbHVt"
    "bjsgfQogIC5hbmFseXNpcy1kaWFsb2cgLm1vZGFsLWhlYWRlciB7IGZsZXgtc2hyaW5rOjA7IHBhZGRpbmc6MTJweCAxNHB4OyB9"
    "CiAgLmFuYWx5c2lzLWRpYWxvZyAubW9kYWwtYm9keSB7IGZsZXg6MSAxIGF1dG87IG1heC1oZWlnaHQ6bm9uZTsgb3ZlcmZsb3ct"
    "eTphdXRvOyAtd2Via2l0LW92ZXJmbG93LXNjcm9sbGluZzp0b3VjaDsgcGFkZGluZzoxMnB4OyB9CiAgLmFuYWx5c2lzLWNoYXJ0"
    "LXdyYXAgeyBoZWlnaHQ6NDR2aDsgbWluLWhlaWdodDoyODBweDsgfQogIC5hbmFseXNpcy1xdWFkLWtleSB7IGdyaWQtdGVtcGxh"
    "dGUtY29sdW1uczoxZnI7IH0KICAuYW5hbHlzaXMtdGFibGUgdGgsIC5hbmFseXNpcy10YWJsZSB0ZCB7IGZvbnQtc2l6ZToxM3B4"
    "OyBwYWRkaW5nOjhweCA2cHg7IH0KfQo8L3N0eWxlPgo8ZGl2IGNsYXNzPSJtb2RhbCBmYWRlIiBpZD0iZXhwZW5zZUFuYWx5c2lz"
    "TW9kYWwiIHRhYmluZGV4PSItMSIgcm9sZT0iZGlhbG9nIiBhcmlhLWxhYmVsbGVkYnk9ImV4cGVuc2VBbmFseXNpc0xhYmVsIiBh"
    "cmlhLWhpZGRlbj0idHJ1ZSI+CiAgPGRpdiBjbGFzcz0ibW9kYWwtZGlhbG9nIG1vZGFsLWxnIGFuYWx5c2lzLWRpYWxvZyIgcm9s"
    "ZT0iZG9jdW1lbnQiPgogICAgPGRpdiBjbGFzcz0ibW9kYWwtY29udGVudCI+CiAgICAgIDxkaXYgY2xhc3M9Im1vZGFsLWhlYWRl"
    "ciI+CiAgICAgICAgPGg1IGNsYXNzPSJtb2RhbC10aXRsZSIgaWQ9ImV4cGVuc2VBbmFseXNpc0xhYmVsIj4KICAgICAgICAgIDxp"
    "IGNsYXNzPSJmYXMgZmEtY2hhcnQtbGluZSIgc3R5bGU9ImNvbG9yOiMxN2EyYjg7Ij48L2k+IEV4cGVuc2VzIHZzIFJlbnQg4oCU"
    "IEFuYWx5c2lzCiAgICAgICAgPC9oNT4KICAgICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3M9ImNsb3NlIiBkYXRhLWRp"
    "c21pc3M9Im1vZGFsIiBhcmlhLWxhYmVsPSJDbG9zZSI+PHNwYW4gYXJpYS1oaWRkZW49InRydWUiPiZ0aW1lczs8L3NwYW4+PC9i"
    "dXR0b24+CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJtb2RhbC1ib2R5Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJyZXBv"
    "cnQteWVhci1iYXIiPgogICAgICAgICAgPHNwYW4gY2xhc3M9InJlcG9ydC15ZWFyLWxhYmVsIj48aSBjbGFzcz0iZmFzIGZhLWNh"
    "bGVuZGFyLWFsdCI+PC9pPiBZZWFyczo8L3NwYW4+CiAgICAgICAgICA8bGFiZWwgY2xhc3M9InJlcG9ydC15ZWFyLWNoayI+PGlu"
    "cHV0IHR5cGU9ImNoZWNrYm94IiBpZD0iYW5hbHlzaXNZZWFyQWxsIiBjaGVja2VkPiBBbGwgeWVhcnM8L2xhYmVsPgogICAgICAg"
    "ICAgPHNwYW4gaWQ9ImFuYWx5c2lzWWVhckxpc3QiIGNsYXNzPSJyZXBvcnQteWVhci1saXN0Ij48L3NwYW4+CiAgICAgICAgPC9k"
    "aXY+CiAgICAgICAgPHAgY2xhc3M9ImFuYWx5c2lzLXN1YiIgaWQ9ImFuYWx5c2lzU3ViIj48L3A+CiAgICAgICAgPGRpdiBpZD0i"
    "YW5hbHlzaXNMb2FkaW5nIiBjbGFzcz0idGV4dC1jZW50ZXIgdGV4dC1tdXRlZCIgc3R5bGU9InBhZGRpbmc6MzBweDsiPgogICAg"
    "ICAgICAgPGkgY2xhc3M9ImZhcyBmYS1zcGlubmVyIGZhLXNwaW4iPjwvaT4gTG9hZGluZy4uLgogICAgICAgIDwvZGl2PgogICAg"
    "ICAgIDxkaXYgaWQ9ImFuYWx5c2lzRW1wdHkiIGNsYXNzPSJ0ZXh0LWNlbnRlciB0ZXh0LW11dGVkIiBzdHlsZT0iZGlzcGxheTpu"
    "b25lOyBwYWRkaW5nOjMwcHg7Ij4KICAgICAgICAgIE5vdCBlbm91Z2ggZGF0YSB0byBjb21wYXJlIHlldC4KICAgICAgICA8L2Rp"
    "dj4KICAgICAgICA8ZGl2IGlkPSJhbmFseXNpc0NvbnRlbnQiIHN0eWxlPSJkaXNwbGF5Om5vbmU7Ij4KICAgICAgICAgIDxkaXYg"
    "Y2xhc3M9ImFuYWx5c2lzLWNoYXJ0LXdyYXAiPjxjYW52YXMgaWQ9ImFuYWx5c2lzQ2hhcnQiPjwvY2FudmFzPjwvZGl2PgogICAg"
    "ICAgICAgPGRpdiBjbGFzcz0iYW5hbHlzaXMtcXVhZC1rZXkiIGlkPSJhbmFseXNpc1F1YWRLZXkiIHN0eWxlPSJkaXNwbGF5Om5v"
    "bmU7Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0icWsgZGFuZ2VyIj48Yj4mIzk4ODg7IFdhdGNoICZtaWRkb3Q7IHRvcC1sZWZ0"
    "PC9iPlN1cnByaXNlIGNvc3RzIG92ZXIgMTAlIG9mIHJlbnQgd2hpbGUgcmVudCBpcyBmbGF0IG9yIGZhbGxpbmcuPC9kaXY+CiAg"
    "ICAgICAgICAgIDxkaXYgY2xhc3M9InFrIj48Yj5Db3N0cyBoaWdoLCByZW50IHJpc2luZyAmbWlkZG90OyB0b3AtcmlnaHQ8L2I+"
    "U3VycHJpc2VzIGFyZSBoaWdoLCBidXQgcmVudCBpcyBncm93aW5nIHRvIGNvdmVyIHRoZW0uPC9kaXY+CiAgICAgICAgICAgIDxk"
    "aXYgY2xhc3M9InFrIj48Yj5SZW50IHN0YWxsZWQgJm1pZGRvdDsgYm90dG9tLWxlZnQ8L2I+U3VycHJpc2UgY29zdHMgbG93LCBi"
    "dXQgcmVudCBpc24ndCBncm93aW5nLjwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJxayBnb29kIj48Yj4mIzEwMDAzOyBI"
    "ZWFsdGh5ICZtaWRkb3Q7IGJvdHRvbS1yaWdodDwvYj5SZW50IGdyb3dpbmcgYW5kIHN1cnByaXNlIGNvc3RzIGxvdy48L2Rpdj4K"
    "ICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0idGFibGUtcmVzcG9uc2l2ZSI+CiAgICAgICAgICAgIDx0YWJs"
    "ZSBjbGFzcz0idGFibGUgdGFibGUtc20gdGFibGUtaG92ZXIgYW5hbHlzaXMtdGFibGUiPgogICAgICAgICAgICAgIDx0aGVhZD4K"
    "ICAgICAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgICAgPHRoPlByb3BlcnR5PC90aD4KICAgICAgICAgICAgICAgICAg"
    "PHRoIGNsYXNzPSJudW0iPlJlbnQ8L3RoPgogICAgICAgICAgICAgICAgICA8dGggY2xhc3M9InRleHQtY2VudGVyIj5MZXQ8L3Ro"
    "PgogICAgICAgICAgICAgICAgICA8dGggY2xhc3M9Im51bSI+QWN0dWFsPC90aD4KICAgICAgICAgICAgICAgICAgPHRoIGNsYXNz"
    "PSJudW0iPiUgb2YgcmVudDwvdGg+CiAgICAgICAgICAgICAgICAgIDx0aCBjbGFzcz0ibnVtIj5SZW50ICZEZWx0YTs8L3RoPgog"
    "ICAgICAgICAgICAgICAgICA8dGggY2xhc3M9InRleHQtY2VudGVyIj5TdGF0dXM8L3RoPgogICAgICAgICAgICAgICAgPC90cj4K"
    "ICAgICAgICAgICAgICA8L3RoZWFkPgogICAgICAgICAgICAgIDx0Ym9keSBpZD0iYW5hbHlzaXNUYWJsZUJvZHkiPjwvdGJvZHk+"
    "CiAgICAgICAgICAgIDwvdGFibGU+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDxwIGNsYXNzPSJ0ZXh0LW11dGVkIHNtYWxs"
    "IG1iLTAiIGlkPSJhbmFseXNpc05vdGUiPjwvcD4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICA8L2Rp"
    "dj4KPC9kaXY+CjxzY3JpcHQ+CihmdW5jdGlvbigpIHsKICAgICd1c2Ugc3RyaWN0JzsKICAgIHZhciBBTkFMWVNJU19VUkwgPSAi"
    "eyUgdXJsICdhY3RfZXhwZW5zZV9hbmFseXNpc19kYXRhJyAlfSI7CiAgICB2YXIgREFOR0VSX1BDVCA9IDEwOwogICAgdmFyIGNo"
    "YXJ0ID0gbnVsbCwgbG9hZGVkID0gZmFsc2UsIERBVEEgPSBudWxsOwoKICAgIGZ1bmN0aW9uIGV1cm8obikgeyByZXR1cm4gJ+KC"
    "rCcgKyBOdW1iZXIobiB8fCAwKS50b0xvY2FsZVN0cmluZygnZW4tSUUnLCB7bWF4aW11bUZyYWN0aW9uRGlnaXRzOiAwfSk7IH0K"
    "ICAgIGZ1bmN0aW9uIHBjdChuKSB7IHJldHVybiAobiA+IDAgPyAnKycgOiAnJykgKyBOdW1iZXIobikudG9GaXhlZCgxKSArICcl"
    "JzsgfQogICAgZnVuY3Rpb24gZXNjYXBlSHRtbChzKXsgcmV0dXJuIFN0cmluZyhzPT1udWxsPycnOnMpLnJlcGxhY2UoLyYvZywn"
    "JmFtcDsnKS5yZXBsYWNlKC88L2csJyZsdDsnKS5yZXBsYWNlKC8+L2csJyZndDsnKTsgfQoKICAgIGZ1bmN0aW9uIGVmZmVjdGl2"
    "ZVllYXJzKCkgewogICAgICAgIHZhciBhbGwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYW5hbHlzaXNZZWFyQWxsJykuY2hl"
    "Y2tlZDsKICAgICAgICB2YXIgcGlja2VkID0gW107CiAgICAgICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbCgnI2FuYWx5c2lz"
    "WWVhckxpc3QgaW5wdXRbdHlwZT1jaGVja2JveF06Y2hlY2tlZCcpLmZvckVhY2goZnVuY3Rpb24oY2IpeyBwaWNrZWQucHVzaChw"
    "YXJzZUludChjYi52YWx1ZSwgMTApKTsgfSk7CiAgICAgICAgaWYgKGFsbCB8fCBwaWNrZWQubGVuZ3RoID09PSAwKSByZXR1cm4g"
    "KERBVEEuYXZhaWxhYmxlX3llYXJzIHx8IFtdKS5zbGljZSgpOwogICAgICAgIHJldHVybiBwaWNrZWQ7CiAgICB9CgogICAgZnVu"
    "Y3Rpb24gYnVpbGRZZWFyQ2hlY2tib3hlcyh5ZWFycykgewogICAgICAgIHZhciBsaXN0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5"
    "SWQoJ2FuYWx5c2lzWWVhckxpc3QnKTsKICAgICAgICBpZiAobGlzdC5kYXRhc2V0LmJ1aWx0ID09PSAnMScpIHJldHVybjsKICAg"
    "ICAgICBsaXN0LmlubmVySFRNTCA9ICcnOwogICAgICAgIHllYXJzLmZvckVhY2goZnVuY3Rpb24oeSkgewogICAgICAgICAgICB2"
    "YXIgbGJsID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGFiZWwnKTsKICAgICAgICAgICAgbGJsLmNsYXNzTmFtZSA9ICdyZXBv"
    "cnQteWVhci1jaGsnOwogICAgICAgICAgICBsYmwuaW5uZXJIVE1MID0gJzxpbnB1dCB0eXBlPSJjaGVja2JveCIgdmFsdWU9Iicg"
    "KyB5ICsgJyI+ICcgKyB5OwogICAgICAgICAgICBsaXN0LmFwcGVuZENoaWxkKGxibCk7CiAgICAgICAgfSk7CiAgICAgICAgbGlz"
    "dC5kYXRhc2V0LmJ1aWx0ID0gJzEnOwogICAgICAgIHZhciBhbGxDYiA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhbmFseXNp"
    "c1llYXJBbGwnKTsKICAgICAgICBhbGxDYi5hZGRFdmVudExpc3RlbmVyKCdjaGFuZ2UnLCBmdW5jdGlvbigpIHsKICAgICAgICAg"
    "ICAgaWYgKGFsbENiLmNoZWNrZWQpIGxpc3QucXVlcnlTZWxlY3RvckFsbCgnaW5wdXRbdHlwZT1jaGVja2JveF0nKS5mb3JFYWNo"
    "KGZ1bmN0aW9uKGNiKXsgY2IuY2hlY2tlZCA9IGZhbHNlOyB9KTsKICAgICAgICAgICAgZWxzZSBpZiAobGlzdC5xdWVyeVNlbGVj"
    "dG9yQWxsKCdpbnB1dFt0eXBlPWNoZWNrYm94XTpjaGVja2VkJykubGVuZ3RoID09PSAwKSB7IGFsbENiLmNoZWNrZWQgPSB0cnVl"
    "OyByZXR1cm47IH0KICAgICAgICAgICAgcmVuZGVyKCk7CiAgICAgICAgfSk7CiAgICAgICAgbGlzdC5xdWVyeVNlbGVjdG9yQWxs"
    "KCdpbnB1dFt0eXBlPWNoZWNrYm94XScpLmZvckVhY2goZnVuY3Rpb24oY2IpIHsKICAgICAgICAgICAgY2IuYWRkRXZlbnRMaXN0"
    "ZW5lcignY2hhbmdlJywgZnVuY3Rpb24oKSB7CiAgICAgICAgICAgICAgICBpZiAoY2IuY2hlY2tlZCkgYWxsQ2IuY2hlY2tlZCA9"
    "IGZhbHNlOwogICAgICAgICAgICAgICAgaWYgKGxpc3QucXVlcnlTZWxlY3RvckFsbCgnaW5wdXRbdHlwZT1jaGVja2JveF06Y2hl"
    "Y2tlZCcpLmxlbmd0aCA9PT0gMCkgYWxsQ2IuY2hlY2tlZCA9IHRydWU7CiAgICAgICAgICAgICAgICByZW5kZXIoKTsKICAgICAg"
    "ICAgICAgfSk7CiAgICAgICAgfSk7CiAgICB9CgogICAgZnVuY3Rpb24gYnViYmxlUmFkaXVzU2NhbGUodmFscykgewogICAgICAg"
    "IHZhciBtaW4gPSBNYXRoLm1pbi5hcHBseShudWxsLCB2YWxzKSwgbWF4ID0gTWF0aC5tYXguYXBwbHkobnVsbCwgdmFscyk7CiAg"
    "ICAgICAgcmV0dXJuIGZ1bmN0aW9uKHYpIHsgcmV0dXJuIChtYXggPT09IG1pbikgPyAxMSA6IDcgKyAodiAtIG1pbikgLyAobWF4"
    "IC0gbWluKSAqIDE1OyB9OwogICAgfQoKICAgIGZ1bmN0aW9uIGxvYWQoKSB7CiAgICAgICAgdmFyIGxvYWRpbmcgPSBkb2N1bWVu"
    "dC5nZXRFbGVtZW50QnlJZCgnYW5hbHlzaXNMb2FkaW5nJyk7CiAgICAgICAgdmFyIGVtcHR5ID0gZG9jdW1lbnQuZ2V0RWxlbWVu"
    "dEJ5SWQoJ2FuYWx5c2lzRW1wdHknKTsKICAgICAgICB2YXIgY29udGVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhbmFs"
    "eXNpc0NvbnRlbnQnKTsKICAgICAgICBsb2FkaW5nLnN0eWxlLmRpc3BsYXkgPSAnYmxvY2snOyBlbXB0eS5zdHlsZS5kaXNwbGF5"
    "ID0gJ25vbmUnOyBjb250ZW50LnN0eWxlLmRpc3BsYXkgPSAnbm9uZSc7CiAgICAgICAgZmV0Y2goQU5BTFlTSVNfVVJMLCB7aGVh"
    "ZGVyczogeydYLVJlcXVlc3RlZC1XaXRoJzogJ1hNTEh0dHBSZXF1ZXN0J319KQogICAgICAgICAgICAudGhlbihmdW5jdGlvbihy"
    "KXsgcmV0dXJuIHIuanNvbigpOyB9KQogICAgICAgICAgICAudGhlbihmdW5jdGlvbihkYXRhKSB7CiAgICAgICAgICAgICAgICBE"
    "QVRBID0gZGF0YTsKICAgICAgICAgICAgICAgIGJ1aWxkWWVhckNoZWNrYm94ZXMoZGF0YS5hdmFpbGFibGVfeWVhcnMgfHwgW10p"
    "OwogICAgICAgICAgICAgICAgbG9hZGluZy5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnOwogICAgICAgICAgICAgICAgcmVuZGVyKCk7"
    "CiAgICAgICAgICAgIH0pCiAgICAgICAgICAgIC5jYXRjaChmdW5jdGlvbihlcnIpIHsKICAgICAgICAgICAgICAgIGxvYWRpbmcu"
    "aW5uZXJIVE1MID0gJzxzcGFuIGNsYXNzPSJ0ZXh0LWRhbmdlciI+RmFpbGVkIHRvIGxvYWQgYW5hbHlzaXMuPC9zcGFuPic7CiAg"
    "ICAgICAgICAgICAgICBjb25zb2xlLmVycm9yKCdBbmFseXNpcyBsb2FkIGVycm9yOicsIGVycik7CiAgICAgICAgICAgIH0pOwog"
    "ICAgfQoKICAgIGZ1bmN0aW9uIHJlbmRlcigpIHsKICAgICAgICBpZiAoIURBVEEpIHJldHVybjsKICAgICAgICB2YXIgZW1wdHkg"
    "PSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYW5hbHlzaXNFbXB0eScpOwogICAgICAgIHZhciBjb250ZW50ID0gZG9jdW1lbnQu"
    "Z2V0RWxlbWVudEJ5SWQoJ2FuYWx5c2lzQ29udGVudCcpOwogICAgICAgIHZhciBxdWFkS2V5ID0gZG9jdW1lbnQuZ2V0RWxlbWVu"
    "dEJ5SWQoJ2FuYWx5c2lzUXVhZEtleScpOwogICAgICAgIHZhciB5ZWFycyA9IGVmZmVjdGl2ZVllYXJzKCkuc2xpY2UoKS5zb3J0"
    "KGZ1bmN0aW9uKGEsYil7IHJldHVybiBhIC0gYjsgfSk7CiAgICAgICAgdmFyIHNpbmdsZSA9IHllYXJzLmxlbmd0aCA8IDI7CiAg"
    "ICAgICAgdmFyIHkwID0geWVhcnNbMF0sIHkxID0geWVhcnNbeWVhcnMubGVuZ3RoIC0gMV07CgogICAgICAgIHZhciByb3dzID0g"
    "W107CiAgICAgICAgKERBVEEucHJvcGVydGllcyB8fCBbXSkuZm9yRWFjaChmdW5jdGlvbihwKSB7CiAgICAgICAgICAgIHZhciBh"
    "ID0gcC55ZWFyc1t5MF0sIGIgPSBwLnllYXJzW3kxXTsKICAgICAgICAgICAgaWYgKCFiKSByZXR1cm47CiAgICAgICAgICAgIHZh"
    "ciByZW50Tm93ID0gYi5yZW50LCBhY3R1YWwgPSBiLmFjdHVhbDsKICAgICAgICAgICAgdmFyIHBjdFJlbnQgPSByZW50Tm93ID8g"
    "KGFjdHVhbCAvIHJlbnROb3cgKiAxMDApIDogbnVsbDsKICAgICAgICAgICAgdmFyIGNoYW5nZSA9ICghc2luZ2xlICYmIGEgJiYg"
    "YS5yZW50KSA/ICgoYi5yZW50IC0gYS5yZW50KSAvIGEucmVudCAqIDEwMCkgOiBudWxsOwogICAgICAgICAgICByb3dzLnB1c2go"
    "ewogICAgICAgICAgICAgICAgaWQ6IHAucHJvcF9pZCwgbmFtZTogcC5wcm9wX25hbWUsCiAgICAgICAgICAgICAgICByZW50OiBy"
    "ZW50Tm93LCBsZXQ6IGIubW9udGhzX2xldCwgYWN0dWFsOiBhY3R1YWwsCiAgICAgICAgICAgICAgICBwY3RSZW50OiBwY3RSZW50"
    "LCBjaGFuZ2U6IGNoYW5nZSwgc291cmNlOiBiLnNvdXJjZSwKICAgICAgICAgICAgICAgIGRhbmdlcjogKHBjdFJlbnQgIT0gbnVs"
    "bCAmJiBwY3RSZW50ID49IERBTkdFUl9QQ1QgJiYgKGNoYW5nZSA9PSBudWxsIHx8IGNoYW5nZSA8PSAwKSkKICAgICAgICAgICAg"
    "fSk7CiAgICAgICAgfSk7CiAgICAgICAgcm93cyA9IHJvd3MuZmlsdGVyKGZ1bmN0aW9uKHIpeyByZXR1cm4gci5yZW50IHx8IHIu"
    "YWN0dWFsOyB9KTsKCiAgICAgICAgaWYgKCFyb3dzLmxlbmd0aCkgeyBlbXB0eS5zdHlsZS5kaXNwbGF5ID0gJ2Jsb2NrJzsgY29u"
    "dGVudC5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnOyByZXR1cm47IH0KICAgICAgICBjb250ZW50LnN0eWxlLmRpc3BsYXkgPSAnYmxv"
    "Y2snOyBlbXB0eS5zdHlsZS5kaXNwbGF5ID0gJ25vbmUnOwoKICAgICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYW5hbHlz"
    "aXNTdWInKS5pbm5lckhUTUwgPSBzaW5nbGUKICAgICAgICAgICAgPyAoJ1JhbmtpbmcgcHJvcGVydGllcyBieSBhY3R1YWwgKGFk"
    "LWhvYykgc3BlbmQgYXMgYSAlIG9mIHJlbnQgZm9yIDxiPicgKyB5MSArICc8L2I+LiBUaWNrIDIrIHllYXJzIHRvIGNvbXBhcmUg"
    "bW92ZW1lbnQuJykKICAgICAgICAgICAgOiAoJ0VhY2ggYnViYmxlIGlzIGEgcHJvcGVydHkuIFggPSByZW50IGNoYW5nZSAnICsg"
    "eTAgKyAn4oaSJyArIHkxICsgJy4gWSA9IGFjdHVhbCBzcGVuZCBhcyAlIG9mIHJlbnQgKCcgKyB5MSArICcpLiBCdWJibGUgc2l6"
    "ZSA9IHJlbnQuJyk7CgogICAgICAgIHF1YWRLZXkuc3R5bGUuZGlzcGxheSA9IHNpbmdsZSA/ICdub25lJyA6ICdncmlkJzsKICAg"
    "ICAgICBpZiAoc2luZ2xlKSByZW5kZXJSYW5raW5nKHJvd3MsIHkxKTsgZWxzZSByZW5kZXJTY2F0dGVyKHJvd3MsIHkwLCB5MSk7"
    "CiAgICAgICAgcmVuZGVyVGFibGUocm93cywgc2luZ2xlKTsKCiAgICAgICAgdmFyIGZsYWdnZWQgPSByb3dzLmZpbHRlcihmdW5j"
    "dGlvbihyKXsgcmV0dXJuIHIuZGFuZ2VyOyB9KS5sZW5ndGg7CiAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FuYWx5"
    "c2lzTm90ZScpLmlubmVySFRNTCA9IGZsYWdnZWQKICAgICAgICAgICAgPyAoJzxpIGNsYXNzPSJmYXMgZmEtZXhjbGFtYXRpb24t"
    "dHJpYW5nbGUiIHN0eWxlPSJjb2xvcjojZGMzNTQ1OyI+PC9pPiAnICsgZmxhZ2dlZCArICcgcHJvcGVydCcgKyAoZmxhZ2dlZD4x"
    "PydpZXMnOid5JykgKyAnIGluIHRoZSB3YXRjaCB6b25lLicpCiAgICAgICAgICAgIDogJ05vIHByb3BlcnRpZXMgaW4gdGhlIHdh"
    "dGNoIHpvbmUuJzsKICAgIH0KCiAgICAvLyBDaGFydC5qcyBpbmxpbmUgcGx1Z2luOiBxdWFkcmFudCB0aW50cywgZGl2aWRlciBs"
    "aW5lcywgY29ybmVyIGxhYmVscy4KICAgIHZhciBxdWFkcmFudFBsdWdpbiA9IHsKICAgICAgICBpZDogJ3F1YWRyYW50cycsCiAg"
    "ICAgICAgYmVmb3JlRGF0YXNldHNEcmF3OiBmdW5jdGlvbihjaGFydCkgewogICAgICAgICAgICB2YXIgeHMgPSBjaGFydC5zY2Fs"
    "ZXMueCwgeXMgPSBjaGFydC5zY2FsZXMueSwgYXJlYSA9IGNoYXJ0LmNoYXJ0QXJlYSwgY3R4ID0gY2hhcnQuY3R4OwogICAgICAg"
    "ICAgICBpZiAoIXhzIHx8ICF5cykgcmV0dXJuOwogICAgICAgICAgICB2YXIgeDAgPSBNYXRoLm1heChhcmVhLmxlZnQsIE1hdGgu"
    "bWluKGFyZWEucmlnaHQsIHhzLmdldFBpeGVsRm9yVmFsdWUoMCkpKTsKICAgICAgICAgICAgdmFyIHkxMCA9IE1hdGgubWF4KGFy"
    "ZWEudG9wLCBNYXRoLm1pbihhcmVhLmJvdHRvbSwgeXMuZ2V0UGl4ZWxGb3JWYWx1ZShEQU5HRVJfUENUKSkpOwogICAgICAgICAg"
    "ICBjdHguc2F2ZSgpOwogICAgICAgICAgICBjdHguZmlsbFN0eWxlID0gJ3JnYmEoMjIwLDUzLDY5LDAuMDYpJzsgICAgICAgICAg"
    "ICAvLyB3YXRjaCAodG9wLWxlZnQpCiAgICAgICAgICAgIGN0eC5maWxsUmVjdChhcmVhLmxlZnQsIGFyZWEudG9wLCB4MCAtIGFy"
    "ZWEubGVmdCwgeTEwIC0gYXJlYS50b3ApOwogICAgICAgICAgICBjdHguZmlsbFN0eWxlID0gJ3JnYmEoNDAsMTY3LDY5LDAuMDUp"
    "JzsgICAgICAgICAgICAvLyBoZWFsdGh5IChib3R0b20tcmlnaHQpCiAgICAgICAgICAgIGN0eC5maWxsUmVjdCh4MCwgeTEwLCBh"
    "cmVhLnJpZ2h0IC0geDAsIGFyZWEuYm90dG9tIC0geTEwKTsKICAgICAgICAgICAgY3R4LnNldExpbmVEYXNoKFs1LCA0XSk7IGN0"
    "eC5saW5lV2lkdGggPSAxOwogICAgICAgICAgICBjdHguc3Ryb2tlU3R5bGUgPSAncmdiYSgwLDAsMCwwLjI4KSc7ICAgICAgICAg"
    "ICAgICAvLyB2ZXJ0aWNhbDogcmVudCBmbGF0CiAgICAgICAgICAgIGN0eC5iZWdpblBhdGgoKTsgY3R4Lm1vdmVUbyh4MCwgYXJl"
    "YS50b3ApOyBjdHgubGluZVRvKHgwLCBhcmVhLmJvdHRvbSk7IGN0eC5zdHJva2UoKTsKICAgICAgICAgICAgY3R4LnN0cm9rZVN0"
    "eWxlID0gJyNkYzM1NDUnOyAgICAgICAgICAgICAgICAgICAgICAgLy8gaG9yaXpvbnRhbDogMTAlIG9mIHJlbnQKICAgICAgICAg"
    "ICAgY3R4LmJlZ2luUGF0aCgpOyBjdHgubW92ZVRvKGFyZWEubGVmdCwgeTEwKTsgY3R4LmxpbmVUbyhhcmVhLnJpZ2h0LCB5MTAp"
    "OyBjdHguc3Ryb2tlKCk7CiAgICAgICAgICAgIGN0eC5yZXN0b3JlKCk7CiAgICAgICAgfSwKICAgICAgICBhZnRlckRhdGFzZXRz"
    "RHJhdzogZnVuY3Rpb24oY2hhcnQpIHsKICAgICAgICAgICAgdmFyIGFyZWEgPSBjaGFydC5jaGFydEFyZWEsIGN0eCA9IGNoYXJ0"
    "LmN0eDsKICAgICAgICAgICAgY3R4LnNhdmUoKTsKICAgICAgICAgICAgY3R4LmZvbnQgPSAnNjAwIDEwcHggc3lzdGVtLXVpLCBz"
    "YW5zLXNlcmlmJzsKICAgICAgICAgICAgY3R4LnRleHRCYXNlbGluZSA9ICd0b3AnOyBjdHgudGV4dEFsaWduID0gJ2xlZnQnOwog"
    "ICAgICAgICAgICBjdHguZmlsbFN0eWxlID0gJ3JnYmEoMTc2LDQyLDU1LDAuOCknOwogICAgICAgICAgICBjdHguZmlsbFRleHQo"
    "J+KaoCBXYXRjaCcsIGFyZWEubGVmdCArIDYsIGFyZWEudG9wICsgNCk7CiAgICAgICAgICAgIGN0eC50ZXh0QWxpZ24gPSAncmln"
    "aHQnOyBjdHguZmlsbFN0eWxlID0gJ3JnYmEoMTA4LDExNywxMjUsMC43NSknOwogICAgICAgICAgICBjdHguZmlsbFRleHQoJ0Nv"
    "c3RzIGhpZ2gsIHJlbnQgcmlzaW5nJywgYXJlYS5yaWdodCAtIDYsIGFyZWEudG9wICsgNCk7CiAgICAgICAgICAgIGN0eC50ZXh0"
    "QmFzZWxpbmUgPSAnYm90dG9tJzsgY3R4LnRleHRBbGlnbiA9ICdsZWZ0JzsKICAgICAgICAgICAgY3R4LmZpbGxUZXh0KCdSZW50"
    "IHN0YWxsZWQnLCBhcmVhLmxlZnQgKyA2LCBhcmVhLmJvdHRvbSAtIDQpOwogICAgICAgICAgICBjdHgudGV4dEFsaWduID0gJ3Jp"
    "Z2h0JzsgY3R4LmZpbGxTdHlsZSA9ICdyZ2JhKDMxLDEyMiw1NSwwLjg1KSc7CiAgICAgICAgICAgIGN0eC5maWxsVGV4dCgn4pyT"
    "IEhlYWx0aHknLCBhcmVhLnJpZ2h0IC0gNiwgYXJlYS5ib3R0b20gLSA0KTsKICAgICAgICAgICAgY3R4LnJlc3RvcmUoKTsKICAg"
    "ICAgICB9CiAgICB9OwoKICAgIGZ1bmN0aW9uIHJlbmRlclNjYXR0ZXIocm93cywgeTAsIHkxKSB7CiAgICAgICAgZG9jdW1lbnQu"
    "cXVlcnlTZWxlY3RvcignLmFuYWx5c2lzLWNoYXJ0LXdyYXAnKS5zdHlsZS5oZWlnaHQgPSAnJzsgIC8vIHVzZSBDU1MgaGVpZ2h0"
    "CiAgICAgICAgdmFyIHB0cyA9IHJvd3MuZmlsdGVyKGZ1bmN0aW9uKHIpeyByZXR1cm4gci5jaGFuZ2UgIT0gbnVsbCAmJiByLnBj"
    "dFJlbnQgIT0gbnVsbDsgfSk7CiAgICAgICAgdmFyIHJTY2FsZSA9IGJ1YmJsZVJhZGl1c1NjYWxlKHB0cy5tYXAoZnVuY3Rpb24o"
    "cil7IHJldHVybiByLnJlbnQgfHwgMDsgfSkpOwogICAgICAgIHZhciBkYXRhID0gcHRzLm1hcChmdW5jdGlvbihyKXsgcmV0dXJu"
    "IHt4OiByLmNoYW5nZSwgeTogci5wY3RSZW50LCByOiByU2NhbGUoci5yZW50KSwgX3I6IHJ9OyB9KTsKICAgICAgICB2YXIgYmcg"
    "PSBwdHMubWFwKGZ1bmN0aW9uKHIpeyByZXR1cm4gci5kYW5nZXIgPyAncmdiYSgyMjAsNTMsNjksMC43NSknIDogJ3JnYmEoMjMs"
    "MTYyLDE4NCwwLjcyKSc7IH0pOwogICAgICAgIHZhciBiZCA9IHB0cy5tYXAoZnVuY3Rpb24ocil7IHJldHVybiByLmRhbmdlciA/"
    "ICcjYjAyYTM3JyA6ICcjMTE3YThiJzsgfSk7CgogICAgICAgIHZhciB4cyA9IHB0cy5tYXAoZnVuY3Rpb24ocil7IHJldHVybiBy"
    "LmNoYW5nZTsgfSk7CiAgICAgICAgdmFyIHhtaW4gPSBNYXRoLm1pbi5hcHBseShudWxsLCB4cy5jb25jYXQoWzBdKSksIHhtYXgg"
    "PSBNYXRoLm1heC5hcHBseShudWxsLCB4cy5jb25jYXQoWzBdKSk7CiAgICAgICAgdmFyIHhwYWQgPSAoeG1heCAtIHhtaW4pICog"
    "MC4xMiB8fCA1OyB4bWluIC09IHhwYWQ7IHhtYXggKz0geHBhZDsKICAgICAgICB2YXIgbWF4UGN0ID0gTWF0aC5tYXguYXBwbHko"
    "bnVsbCwgcHRzLm1hcChmdW5jdGlvbihyKXsgcmV0dXJuIHIucGN0UmVudDsgfSkuY29uY2F0KFtEQU5HRVJfUENUICsgMl0pKTsK"
    "ICAgICAgICB2YXIgeW1heCA9IE1hdGguY2VpbChtYXhQY3QgKiAxLjEpOwoKICAgICAgICBpZiAoY2hhcnQpIGNoYXJ0LmRlc3Ry"
    "b3koKTsKICAgICAgICB2YXIgY3R4ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FuYWx5c2lzQ2hhcnQnKS5nZXRDb250ZXh0"
    "KCcyZCcpOwogICAgICAgIGNoYXJ0ID0gbmV3IENoYXJ0KGN0eCwgewogICAgICAgICAgICBkYXRhOiB7IGRhdGFzZXRzOiBbeyB0"
    "eXBlOiAnYnViYmxlJywgbGFiZWw6ICdQcm9wZXJ0aWVzJywgZGF0YTogZGF0YSwgYmFja2dyb3VuZENvbG9yOiBiZywgYm9yZGVy"
    "Q29sb3I6IGJkLCBib3JkZXJXaWR0aDogMSB9XSB9LAogICAgICAgICAgICBvcHRpb25zOiB7CiAgICAgICAgICAgICAgICByZXNw"
    "b25zaXZlOiB0cnVlLCBtYWludGFpbkFzcGVjdFJhdGlvOiBmYWxzZSwKICAgICAgICAgICAgICAgIGxheW91dDogeyBwYWRkaW5n"
    "OiB7IHRvcDogNCwgcmlnaHQ6IDYgfSB9LAogICAgICAgICAgICAgICAgc2NhbGVzOiB7CiAgICAgICAgICAgICAgICAgICAgeDog"
    "eyBtaW46IHhtaW4sIG1heDogeG1heCwgdGl0bGU6IHtkaXNwbGF5OiB0cnVlLCB0ZXh0OiAnUmVudCBjaGFuZ2UgKCUpJ30sCiAg"
    "ICAgICAgICAgICAgICAgICAgICAgICB0aWNrczogeyBjYWxsYmFjazogZnVuY3Rpb24odil7IHJldHVybiAodj4wPycrJzonJykg"
    "KyB2ICsgJyUnOyB9IH0gfSwKICAgICAgICAgICAgICAgICAgICB5OiB7IG1pbjogMCwgbWF4OiB5bWF4LCB0aXRsZToge2Rpc3Bs"
    "YXk6IHRydWUsIHRleHQ6ICdBY3R1YWwgZXhwZW5zZXMgKCUgb2YgcmVudCknfSwKICAgICAgICAgICAgICAgICAgICAgICAgIHRp"
    "Y2tzOiB7IGNhbGxiYWNrOiBmdW5jdGlvbih2KXsgcmV0dXJuIHYgKyAnJSc7IH0gfSB9CiAgICAgICAgICAgICAgICB9LAogICAg"
    "ICAgICAgICAgICAgcGx1Z2luczogewogICAgICAgICAgICAgICAgICAgIGxlZ2VuZDogeyBkaXNwbGF5OiBmYWxzZSB9LAogICAg"
    "ICAgICAgICAgICAgICAgIHRvb2x0aXA6IHsgY2FsbGJhY2tzOiB7IGxhYmVsOiBmdW5jdGlvbihjKSB7CiAgICAgICAgICAgICAg"
    "ICAgICAgICAgIHZhciByID0gYy5yYXcgJiYgYy5yYXcuX3I7IGlmICghcikgcmV0dXJuICcnOwogICAgICAgICAgICAgICAgICAg"
    "ICAgICByZXR1cm4gW3IubmFtZSwgJ1JlbnQgY2hhbmdlOiAnICsgKHIuY2hhbmdlPT1udWxsPyfigJQnOnBjdChyLmNoYW5nZSkp"
    "LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdBY3R1YWwvcmVudDogJyArIHIucGN0UmVudC50b0ZpeGVkKDEpICsg"
    "JyUnLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdSZW50OiAnICsgZXVybyhyLnJlbnQpICsgJyAgQWN0dWFsOiAn"
    "ICsgZXVybyhyLmFjdHVhbCldOwogICAgICAgICAgICAgICAgICAgIH0gfSB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAg"
    "IH0sCiAgICAgICAgICAgIHBsdWdpbnM6IFtxdWFkcmFudFBsdWdpbl0KICAgICAgICB9KTsKICAgIH0KCiAgICBmdW5jdGlvbiBy"
    "ZW5kZXJSYW5raW5nKHJvd3MsIHllYXIpIHsKICAgICAgICB2YXIgcmsgPSByb3dzLmZpbHRlcihmdW5jdGlvbihyKXsgcmV0dXJu"
    "IHIucGN0UmVudCAhPSBudWxsOyB9KS5zbGljZSgpLnNvcnQoZnVuY3Rpb24oYSxiKXsgcmV0dXJuIGIucGN0UmVudCAtIGEucGN0"
    "UmVudDsgfSk7CiAgICAgICAgdmFyIGxhYmVscyA9IHJrLm1hcChmdW5jdGlvbihyKXsgcmV0dXJuIHIubmFtZTsgfSk7CiAgICAg"
    "ICAgdmFyIHZhbHMgPSByay5tYXAoZnVuY3Rpb24ocil7IHJldHVybiArci5wY3RSZW50LnRvRml4ZWQoMSk7IH0pOwogICAgICAg"
    "IHZhciBiZyA9IHJrLm1hcChmdW5jdGlvbihyKXsgcmV0dXJuIHIucGN0UmVudCA+PSBEQU5HRVJfUENUID8gJ3JnYmEoMjIwLDUz"
    "LDY5LDAuOCknIDogJyMxN2EyYjgnOyB9KTsKICAgICAgICB2YXIgd3JhcCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5hbmFs"
    "eXNpcy1jaGFydC13cmFwJyk7CiAgICAgICAgd3JhcC5zdHlsZS5oZWlnaHQgPSBNYXRoLm1heCgyNDAsIHJrLmxlbmd0aCAqIDMw"
    "ICsgNTApICsgJ3B4JzsKICAgICAgICBpZiAoY2hhcnQpIGNoYXJ0LmRlc3Ryb3koKTsKICAgICAgICB2YXIgY3R4ID0gZG9jdW1l"
    "bnQuZ2V0RWxlbWVudEJ5SWQoJ2FuYWx5c2lzQ2hhcnQnKS5nZXRDb250ZXh0KCcyZCcpOwogICAgICAgIGNoYXJ0ID0gbmV3IENo"
    "YXJ0KGN0eCwgewogICAgICAgICAgICB0eXBlOiAnYmFyJywKICAgICAgICAgICAgZGF0YTogeyBsYWJlbHM6IGxhYmVscywgZGF0"
    "YXNldHM6IFt7IGxhYmVsOiAnQWN0dWFsICUgb2YgcmVudCcsIGRhdGE6IHZhbHMsIGJhY2tncm91bmRDb2xvcjogYmcsIG1heEJh"
    "clRoaWNrbmVzczogMjIgfV0gfSwKICAgICAgICAgICAgb3B0aW9uczogewogICAgICAgICAgICAgICAgaW5kZXhBeGlzOiAneScs"
    "IHJlc3BvbnNpdmU6IHRydWUsIG1haW50YWluQXNwZWN0UmF0aW86IGZhbHNlLAogICAgICAgICAgICAgICAgc2NhbGVzOiB7IHg6"
    "IHsgYmVnaW5BdFplcm86IHRydWUsIHRpdGxlOiB7ZGlzcGxheTp0cnVlLCB0ZXh0OidBY3R1YWwgZXhwZW5zZXMgKCUgb2YgcmVu"
    "dCkg4oCUICcgKyB5ZWFyfSwgdGlja3M6IHsgY2FsbGJhY2s6IGZ1bmN0aW9uKHYpeyByZXR1cm4gdiArICclJzsgfSB9IH0gfSwK"
    "ICAgICAgICAgICAgICAgIHBsdWdpbnM6IHsgbGVnZW5kOiB7IGRpc3BsYXk6ZmFsc2UgfSwgdG9vbHRpcDogeyBjYWxsYmFja3M6"
    "IHsgbGFiZWw6IGZ1bmN0aW9uKGMpeyByZXR1cm4gYy5wYXJzZWQueCArICclIG9mIHJlbnQnOyB9IH0gfSB9CiAgICAgICAgICAg"
    "IH0KICAgICAgICB9KTsKICAgIH0KCiAgICBmdW5jdGlvbiByZW5kZXJUYWJsZShyb3dzLCBzaW5nbGUpIHsKICAgICAgICB2YXIg"
    "Ym9keSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhbmFseXNpc1RhYmxlQm9keScpOwogICAgICAgIGJvZHkuaW5uZXJIVE1M"
    "ID0gJyc7CiAgICAgICAgcm93cy5zbGljZSgpLnNvcnQoZnVuY3Rpb24oYSxiKXsgcmV0dXJuIChiLnBjdFJlbnR8fDApIC0gKGEu"
    "cGN0UmVudHx8MCk7IH0pLmZvckVhY2goZnVuY3Rpb24ocikgewogICAgICAgICAgICB2YXIgdHIgPSBkb2N1bWVudC5jcmVhdGVF"
    "bGVtZW50KCd0cicpOwogICAgICAgICAgICBpZiAoci5kYW5nZXIpIHRyLmNsYXNzTmFtZSA9ICdkYW5nZXItcm93JzsKICAgICAg"
    "ICAgICAgdmFyIGNoZyA9IChyLmNoYW5nZSA9PSBudWxsKSA/ICc8c3BhbiBjbGFzcz0iYW5hbHlzaXMtc3JjIj7igJQ8L3NwYW4+"
    "JwogICAgICAgICAgICAgICAgICAgICA6ICgnPHNwYW4gc3R5bGU9ImNvbG9yOicgKyAoci5jaGFuZ2UgPCAwID8gJyNkYzM1NDUn"
    "IDogJyMxZjdhMzcnKSArICc7Ij4nICsgcGN0KHIuY2hhbmdlKSArICc8L3NwYW4+Jyk7CiAgICAgICAgICAgIHZhciBwY3RDZWxs"
    "ID0gKHIucGN0UmVudCA9PSBudWxsKSA/ICfigJQnIDogci5wY3RSZW50LnRvRml4ZWQoMSkgKyAnJSc7CiAgICAgICAgICAgIHRy"
    "LmlubmVySFRNTCA9CiAgICAgICAgICAgICAgICAnPHRkPicgKyBlc2NhcGVIdG1sKHIubmFtZSkgKyAnIDxzcGFuIGNsYXNzPSJh"
    "bmFseXNpcy1zcmMiPignICsgci5zb3VyY2UgKyAnKTwvc3Bhbj48L3RkPicgKwogICAgICAgICAgICAgICAgJzx0ZCBjbGFzcz0i"
    "bnVtIj4nICsgZXVybyhyLnJlbnQpICsgJzwvdGQ+JyArCiAgICAgICAgICAgICAgICAnPHRkIGNsYXNzPSJ0ZXh0LWNlbnRlciI+"
    "JyArIHIubGV0ICsgJy8xMjwvdGQ+JyArCiAgICAgICAgICAgICAgICAnPHRkIGNsYXNzPSJudW0iPicgKyBldXJvKHIuYWN0dWFs"
    "KSArICc8L3RkPicgKwogICAgICAgICAgICAgICAgJzx0ZCBjbGFzcz0ibnVtIj4nICsgcGN0Q2VsbCArICc8L3RkPicgKwogICAg"
    "ICAgICAgICAgICAgJzx0ZCBjbGFzcz0ibnVtIj4nICsgY2hnICsgJzwvdGQ+JyArCiAgICAgICAgICAgICAgICAnPHRkIGNsYXNz"
    "PSJ0ZXh0LWNlbnRlciI+JyArIChyLmRhbmdlciA/ICc8c3BhbiBjbGFzcz0iYW5hbHlzaXMtZmxhZyB3YXJuIj5XYXRjaDwvc3Bh"
    "bj4nIDogJzxzcGFuIGNsYXNzPSJhbmFseXNpcy1mbGFnIG9rIj5PSzwvc3Bhbj4nKSArICc8L3RkPic7CiAgICAgICAgICAgIGJv"
    "ZHkuYXBwZW5kQ2hpbGQodHIpOwogICAgICAgIH0pOwogICAgfQoKICAgIC8vIExvYWQgb24gZmlyc3Qgb3BlbiAodmFuaWxsYSBs"
    "aXN0ZW5lciDigJQgc2FtZSByZWFzb24gYXMgdGhlIFJlcG9ydCBtb2RhbCkuCiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxs"
    "KCdbZGF0YS10YXJnZXQ9IiNleHBlbnNlQW5hbHlzaXNNb2RhbCJdJykuZm9yRWFjaChmdW5jdGlvbihidG4pIHsKICAgICAgICBi"
    "dG4uYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCBmdW5jdGlvbigpIHsKICAgICAgICAgICAgaWYgKCFsb2FkZWQpIHsgbG9hZGVk"
    "ID0gdHJ1ZTsgbG9hZCgpOyB9CiAgICAgICAgICAgIGVsc2UgaWYgKGNoYXJ0KSB7IHNldFRpbWVvdXQoZnVuY3Rpb24oKXsgY2hh"
    "cnQucmVzaXplKCk7IH0sIDI1MCk7IH0KICAgICAgICB9KTsKICAgIH0pOwp9KSgpOwo8L3NjcmlwdD4K"
])).decode('utf-8')


def read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()


def find_template(root):
    for dp, _, files in os.walk(root):
        if '__pycache__' in dp:
            continue
        for fn in files:
            if fn.endswith('.html'):
                p = os.path.join(dp, fn)
                try:
                    if 'id="expenseAnalysisModal"' in read(p):
                        return p
                except Exception:
                    pass
    return None


def main():
    root = os.getcwd()
    if not os.path.exists(os.path.join(root, 'manage.py')):
        print("!! Run from the project root (the folder with manage.py).")
        sys.exit(1)

    tpl = find_template(root)
    if not tpl:
        print("!! No template contains the Analysis modal. Run "
              "install_analysis_modal.py first.")
        sys.exit(1)
    print("Template: " + tpl + (" (dry run)" if DRY else ""))
    text = read(tpl)

    key = text.find('EXPENSES vs RENT')
    start = text.rfind('<!--', 0, key) if key != -1 else -1
    end = text.rfind('{% endblock %}')
    if start == -1 or end == -1 or start >= end:
        print("!! Couldn't locate the existing Analysis block boundaries. "
              "Nothing changed.")
        sys.exit(1)

    new_text = text[:start] + NEW_BLOCK + "\n\n" + text[end:]
    if new_text == text:
        print("   [skip] already up to date.")
        return
    if DRY:
        print("   [dry-run] would replace the Analysis modal block "
              "(%d chars -> %d chars). Nothing written." % (end - start, len(NEW_BLOCK)))
        return

    bak = tpl + '.bak_analysis_update'
    if not os.path.exists(bak):
        with open(bak, 'w', encoding='utf-8') as f:
            f.write(text)
    with open(tpl, 'w', encoding='utf-8') as f:
        f.write(new_text)
    print("   [OK] Analysis modal block updated (backup: " +
          os.path.basename(tpl) + ".bak_analysis_update)")
    print("\nDone. Hard-refresh the Expenses page and reopen Analysis.")


if __name__ == '__main__':
    main()