# Generated by Django 5.1.4 on 2025-01-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="issues",
            fields=[
                ("issues_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "issues_heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "issues_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issues_date_logged", models.DateField(blank=True, null=True)),
                (
                    "issues_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "issues_resolution_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "issues_resolving_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "issues",
            },
        ),
        migrations.CreateModel(
            name="petty",
            fields=[
                ("petty_cash_id", models.AutoField(primary_key=True, serialize=False)),
                ("petty_cash_date", models.DateField(blank=True, null=True)),
                (
                    "petty_cash_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "petty_cash_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "petty_cash_dr_cr",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
            ],
            options={
                "db_table": "petty_cash",
            },
        ),
        migrations.CreateModel(
            name="props",
            fields=[
                ("prop_id", models.AutoField(primary_key=True, serialize=False)),
                ("prop_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "prop_address1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_suburb",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prop_city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "prop_province",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prop_pcode", models.CharField(blank=True, max_length=255, null=True)),
                ("prop_floor_area", models.IntegerField(blank=True, null=True)),
                ("prop_year_built", models.IntegerField(blank=True, null=True)),
                (
                    "prop_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_available_for_rent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_title_deed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_title_deed_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_electricity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prop_water", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "prop_refuse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_property_tax",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_sewerage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "prop",
            },
        ),
        migrations.CreateModel(
            name="issues_details",
            fields=[
                (
                    "issues_details_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "issues_details_comment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "issues_details_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issues_details_date", models.DateField(blank=True, null=True)),
                (
                    "issues",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.issues"
                    ),
                ),
            ],
            options={
                "db_table": "issues_details",
            },
        ),
        migrations.AddField(
            model_name="issues",
            name="prop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.props"
            ),
        ),
        migrations.CreateModel(
            name="tenant",
            fields=[
                ("tenant_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tenant_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_contact_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tenant_deposit", models.IntegerField(blank=True, null=True)),
                ("tenant_lease_start_date", models.DateField(blank=True, null=True)),
                ("tenant_lease_end_date", models.DateField(blank=True, null=True)),
                (
                    "tenant_rental_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_renewal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tenant_renewal_period", models.IntegerField(blank=True, null=True)),
                ("tenant_rent", models.IntegerField(blank=True, null=True)),
                ("tenant_levies", models.IntegerField(blank=True, null=True)),
                ("tenant_payment_terms", models.IntegerField(blank=True, null=True)),
                (
                    "tenant_current",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_lease_agreement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.props"
                    ),
                ),
            ],
            options={
                "db_table": "tenant",
            },
        ),
        migrations.CreateModel(
            name="invoices",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_paid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
            },
        ),
    ]
