# Generated by Django 5.1.4 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_tenant_tenant_deposit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="tenant_deposit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_levies",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_payment_terms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_renewal_period",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_rent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
