# Generated by Django 5.1.4 on 2025-01-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_tenant_tenant_deposit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_contact_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "supplier",
            },
        ),
    ]
