# Generated by Django 5.1.4 on 2025-01-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="supplier_country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
