# Generated by Django 5.1.4 on 2025-02-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_supplier_supplier_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="supplier",
        ),
    ]
