# Generated by Django 5.1.4 on 2025-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petty",
            name="petty_cash_description",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
