# Generated by Django 5.1.4 on 2025-05-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_petty_petty_cash_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="prop_values",
            fields=[
                ("prop_values_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prop_values_purchase_price",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "prop_values_current_value",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.props"
                    ),
                ),
            ],
            options={
                "db_table": "prop_values",
            },
        ),
    ]
