# Generated by Django 5.1.4 on 2025-05-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_prop_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="revenue_line_types",
            fields=[
                (
                    "revenue_line_types_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "revenue_line_types_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "revenue_line_types_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "revenue_line_types",
            },
        ),
        migrations.CreateModel(
            name="revenue_types",
            fields=[
                (
                    "revenue_types_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "revenue_types_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "revenue_types_jan",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_feb",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_mar",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_apr",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_may",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_jun",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_jul",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_aug",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_sep",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_oct",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_nov",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "revenue_types_dec",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
            ],
            options={
                "db_table": "revenue_types",
            },
        ),
        migrations.CreateModel(
            name="revenue",
            fields=[
                ("revenue_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "revenue_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_jan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_feb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_mar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_may",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_jun",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_jul",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_aug",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_sep",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_oct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_nov",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "revenue_dec",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.props"
                    ),
                ),
                (
                    "revenue_line_types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.revenue_line_types",
                    ),
                ),
                (
                    "revenue_types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.revenue_types",
                    ),
                ),
            ],
            options={
                "db_table": "revenue",
            },
        ),
    ]
