# Generated by Django 5.1.4 on 2025-05-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_revenue_line_types_revenue_types_revenue"),
    ]

    operations = [
        migrations.CreateModel(
            name="expense_line_types",
            fields=[
                (
                    "expense_line_types_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "expense_line_types_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_line_types_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_line_types_prorata",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_line_types_pr_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "db_table": "expense_line_types",
            },
        ),
        migrations.CreateModel(
            name="expense_types",
            fields=[
                (
                    "expense_types_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "expense_types_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_types_jan",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_feb",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_mar",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_apr",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_may",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_jun",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_jul",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_aug",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_sep",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_oct",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_nov",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "expense_types_dec",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
            ],
            options={
                "db_table": "expense_types",
            },
        ),
        migrations.CreateModel(
            name="expense",
            fields=[
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "expense_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_jan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_feb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_mar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_may",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_jun",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_jul",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_aug",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_sep",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_oct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_nov",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expense_dec",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.props"
                    ),
                ),
                (
                    "expense_line_types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.expense_line_types",
                    ),
                ),
                (
                    "expense_types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.expense_types",
                    ),
                ),
            ],
            options={
                "db_table": "expense",
            },
        ),
    ]
