# Generated by Django 5.1.4 on 2025-05-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_expense_line_types_expense_types_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="act_expense",
            fields=[
                ("act_expense_id", models.AutoField(primary_key=True, serialize=False)),
                ("act_expense_date", models.DateField(blank=True, null=True)),
                (
                    "act_expense_description",
                    models.CharField(blank=True, max_length=55, null=True),
                ),
                (
                    "act_expense_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "act_expense_approved",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "act_expense_paid",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.props"
                    ),
                ),
            ],
            options={
                "db_table": "act_expense",
            },
        ),
    ]
