# Generated by Django 5.1.4 on 2025-06-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_act_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="act_expense",
            name="act_expense_document",
            field=models.FileField(blank=True, null=True, upload_to="expense_docs/"),
        ),
    ]
