# Generated by Django 5.1.4 on 2025-06-03 04:21

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_act_expense_act_expense_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act_expense",
            name="act_expense_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pages.models.expense_document_upload_path,
            ),
        ),
    ]
