# Generated by Django 5.1.4 on 2025-06-03 12:10

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_act_expense_act_expense_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="props",
            name="prop_title_deed",
            field=models.FileField(
                blank=True, null=True, upload_to=pages.models.title_deed_upload_path
            ),
        ),
    ]
