# Generated by Django 5.1.4 on 2025-06-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_alter_props_prop_title_deed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="props",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
    ]
