# Generated by Django 5.1.4 on 2025-06-04 03:48

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_alter_props_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_lease_agreement_status",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Lease Agreement Status",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_lease_agreement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pages.models.lease_agreement_upload_path,
                verbose_name="Lease Agreement Document",
            ),
        ),
    ]
