# Generated by Django 5.1.4 on 2025-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_alter_tenant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="props",
            name="prop_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="props",
            name="prop_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
