# Generated by Django 5.1.4 on 2025-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_props_prop_latitude_props_prop_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tenant_renewal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("declined", "Declined"),
                    ("new_lease_signed", "New Lease Signed"),
                ],
                default="pending",
                max_length=20,
                null=True,
                verbose_name="Renewal Status",
            ),
        ),
    ]
