# Generated by Django 5.1.4 on 2025-07-30 04:39

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_tenant_tenant_renewal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_expected_completion_date', models.DateField(blank=True, null=True)),
                ('project_actual_completion_date', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_total_budgeted_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('project_total_actual_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('project_created_date', models.DateTimeField(auto_now_add=True)),
                ('project_updated_date', models.DateTimeField(auto_now=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.props')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-project_created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_start_date', models.DateField(blank=True, null=True)),
                ('task_expected_completion_date', models.DateField(blank=True, null=True)),
                ('task_actual_completion_date', models.DateField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Not Started', max_length=20, null=True)),
                ('task_priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10, null=True)),
                ('task_budgeted_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('task_actual_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('task_assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('task_created_date', models.DateTimeField(auto_now_add=True)),
                ('task_updated_date', models.DateTimeField(auto_now=True)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pages.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='pages.project')),
            ],
            options={
                'verbose_name': 'Project Task',
                'verbose_name_plural': 'Project Tasks',
                'db_table': 'project_tasks',
                'ordering': ['task_start_date', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=pages.models.project_document_upload_path)),
                ('document_uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('document_uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='pages.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='pages.projecttask')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'db_table': 'project_documents',
                'ordering': ['-document_uploaded_date'],
            },
        ),
    ]
