# Generated by Django 5.1.4 on 2025-07-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_project_projecttask_projectdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projecttask",
            options={
                "ordering": ["task_start_date", "task_name"],
                "verbose_name": "Project Task",
                "verbose_name_plural": "Project Tasks",
            },
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.project"
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="task_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="task_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
