# Generated by Django 5.1.4 on 2025-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_alter_projecttask_options_alter_projecttask_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="task_progress_percentage",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Progress percentage (0-100). Only used for subtasks.",
                null=True,
            ),
        ),
    ]
