# Generated by Django 5.1.4 on 2025-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_projecttask_task_progress_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_description_greek",
            field=models.TextField(
                blank=True,
                help_text="Greek translation of project description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name_greek",
            field=models.CharField(
                blank=True,
                help_text="Greek translation of project name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_description_greek",
            field=models.TextField(
                blank=True, help_text="Greek translation of task description", null=True
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_name_greek",
            field=models.CharField(
                blank=True,
                help_text="Greek translation of task name",
                max_length=255,
                null=True,
            ),
        ),
    ]
