# Generated by Django 5.1.4 on 2025-10-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_add_greek_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id', 'ID')], max_length=10)),
                ('country_of_issue', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document_file', models.FileField(blank=True, null=True, upload_to='passports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
