# Generated by Django 5.1.4 on 2025-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='document_number',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
