# Generated by Django 5.1.4 on 2025-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_passport_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('renewal', 'Applied for Renewal'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
