# Generated by Django 5.1.4 on 2025-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_passport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id', 'ID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('renewal', 'Applied for Renewal'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
