# Generated by Django 5.1.4 on 2025-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_passport_document_type_alter_passport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id', 'ID'), ('drivers_license', "Driver's License"), ('visa', 'Visa'), ('arc', 'Alien Registration Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passport',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
