# Generated by Django 5.1.4 on 2025-10-30 14:20

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_passport_date_of_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('ingredient_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Vegetables, Poultry, Dairy', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
                'db_table': 'ingredient_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('measurement_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name (e.g., teaspoon, cup, gram)', max_length=50)),
                ('abbreviation', models.CharField(blank=True, help_text='Short form (e.g., tsp, cup, g)', max_length=10, null=True)),
                ('unit_type', models.CharField(choices=[('volume', 'Volume'), ('weight', 'Weight'), ('count', 'Count'), ('other', 'Other')], default='other', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Measurement Unit',
                'verbose_name_plural': 'Measurement Units',
                'db_table': 'measurement_units',
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('recipe_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Pasta, Salad, Asian, Burgers', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Category',
                'verbose_name_plural': 'Recipe Categories',
                'db_table': 'recipe_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCourse',
            fields=[
                ('recipe_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Starter, Main, Dessert, Snack', max_length=50, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Course',
                'verbose_name_plural': 'Recipe Courses',
                'db_table': 'recipe_courses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Passport/ID Document', 'verbose_name_plural': 'Passport/ID Documents'},
        ),
        migrations.AlterModelTable(
            name='passport',
            table='passports',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Onion, Chicken Breast', max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Storage tips, substitutions, etc.', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ingredientcategory')),
                ('default_unit', models.ForeignKey(blank=True, help_text='Default measurement unit for this ingredient', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.measurementunit')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(help_text='Name of the recipe', max_length=255)),
                ('recipe_description', models.TextField(blank=True, help_text='Brief description or introduction', null=True)),
                ('prep_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('cook_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('total_time', models.IntegerField(blank=True, help_text='Total time in minutes (auto-calculated if not provided)', null=True)),
                ('servings', models.IntegerField(default=4, help_text='Number of servings')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('main_protein', models.CharField(blank=True, choices=[('None', 'None / Vegetarian'), ('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('Fish', 'Fish'), ('Seafood', 'Seafood'), ('Turkey', 'Turkey'), ('Duck', 'Duck'), ('Other', 'Other')], default='None', max_length=50, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to=pages.models.recipe_image_upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this recipe', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.recipecategory')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.recipecourse')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipes',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('recipe_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, help_text='Amount (use decimal: 1.5 for 1½)', max_digits=8)),
                ('preparation_note', models.CharField(blank=True, help_text='e.g., diced, chopped finely, at room temperature', max_length=255, null=True)),
                ('ingredient_order', models.IntegerField(default=0, help_text='Display order in recipe')),
                ('ingredient_group', models.CharField(blank=True, help_text='e.g., "For the sauce", "For garnish"', max_length=100, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='pages.recipe')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.measurementunit')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'db_table': 'recipe_ingredients',
                'ordering': ['ingredient_group', 'ingredient_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('recipe_instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(help_text='Step number in sequence')),
                ('instruction_text', models.TextField(help_text='Detailed instruction for this step')),
                ('instruction_group', models.CharField(blank=True, help_text='e.g., "Preparation", "Cooking", "Assembly"', max_length=100, null=True)),
                ('time_estimate', models.IntegerField(blank=True, help_text='Estimated time for this step in minutes', null=True)),
                ('step_image', models.ImageField(blank=True, null=True, upload_to=pages.models.instruction_image_upload_path)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='pages.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Instruction',
                'verbose_name_plural': 'Recipe Instructions',
                'db_table': 'recipe_instructions',
                'ordering': ['step_number'],
            },
        ),
    ]
