# Generated by Django 5.1.4 on 2025-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_ingredientcategory_measurementunit_recipecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProtein',
            fields=[
                ('custom_protein_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Protein',
                'verbose_name_plural': 'Custom Proteins',
                'db_table': 'custom_proteins',
                'ordering': ['name'],
            },
        ),
    ]
