# Generated by Django 5.1.4 on 2025-10-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_customprotein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='main_protein',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='pages.recipecategory'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='pages.recipecourse'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='pages.customprotein'),
        ),
    ]
