# Generated by Django 5.1.4 on 2025-11-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_recipe_category_remove_recipe_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_extracted_data',
            field=models.JSONField(blank=True, help_text='Raw AI extraction data including structured ingredients', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_ai_imported',
            field=models.BooleanField(default=False, help_text='Flag to indicate if recipe was imported via AI'),
        ),
        migrations.CreateModel(
            name='RecipeIngredientText',
            fields=[
                ('recipe_ingredient_text_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_text', models.CharField(help_text='Plain text ingredient (e.g., "2 cups flour, sifted")', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_ingredients', to='pages.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient (Text)',
                'verbose_name_plural': 'Recipe Ingredients (Text)',
                'db_table': 'recipe_ingredient_text',
                'ordering': ['order'],
            },
        ),
    ]
