# Generated by Django 5.1.4 on 2025-11-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_recipe_ai_extracted_data_recipe_is_ai_imported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationMethod',
            fields=[
                ('preparation_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., chopped, diced, minced, grated', max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Preparation Method',
                'verbose_name_plural': 'Preparation Methods',
                'db_table': 'preparation_methods',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='preparation_note',
            field=models.CharField(blank=True, help_text='Additional preparation notes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='preparation',
            field=models.ForeignKey(blank=True, help_text='e.g., diced, chopped finely, minced', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.preparationmethod'),
        ),
    ]
