# Generated by Django 5.1.4 on 2025-11-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_preparationmethod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredienttext',
            options={'ordering': ['ingredient_group', 'order'], 'verbose_name': 'Recipe Ingredient (Text)', 'verbose_name_plural': 'Recipe Ingredients (Text)'},
        ),
        migrations.AddField(
            model_name='recipeingredienttext',
            name='ingredient_group',
            field=models.CharField(blank=True, help_text='Ingredient grouping', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredienttext',
            name='ingredient_text',
            field=models.CharField(help_text='Plain text ingredient', max_length=500),
        ),
    ]
