# Generated by Django 5.1.4 on 2025-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_recipeingredienttext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(choices=[('General', 'General'), ('Demetri & Angy', 'Demetri & Angy'), ('Erene', 'Erene'), ('Alexandra', 'Alexandra')], default='General', help_text='Recipe author or source', max_length=50),
        ),
    ]
