# Generated by Django 5.1.4 on 2025-11-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_recipe_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('meal_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('meal_plan_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='pages.mealplan')),
            ],
            options={
                'db_table': 'meal_plan_days',
                'ordering': ['date'],
                'unique_together': {('meal_plan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MealPlanRecipe',
            fields=[
                ('meal_plan_recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('servings', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('meal_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='pages.mealplanday')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recipe')),
            ],
            options={
                'db_table': 'meal_plan_recipes',
                'ordering': ['sort_order', 'meal_plan_recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('unit_conversion_id', models.AutoField(primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='pages.measurementunit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='pages.measurementunit')),
            ],
            options={
                'db_table': 'unit_conversions',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
