# Generated by Django 5.1.4 on 2025-11-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_mealplan_mealplanday_mealplanrecipe_unitconversion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='specific_ingredient',
            field=models.ForeignKey(blank=True, help_text='If set, this conversion only applies to this specific ingredient. If NULL, conversion is generic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_conversions', to='pages.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('from_unit', 'to_unit', 'specific_ingredient')},
        ),
    ]
