# Generated by Django 5.1.4 on 2025-12-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_alter_unitconversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementunit',
            name='abbreviation_plural',
            field=models.CharField(blank=True, help_text='Plural short form (e.g., tsp, cups, g)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='name_plural',
            field=models.CharField(blank=True, help_text='Plural name (e.g., teaspoons, cups, grams)', max_length=50),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Singular short form (e.g., tsp, cup, g)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(help_text='Singular name (e.g., teaspoon, cup, gram)', max_length=50),
        ),
    ]
