# Generated by Django 5.1.4 on 2025-12-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_populate_unit_plurals'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date the vacancy period began (usually previous lease end date)')),
                ('end_date', models.DateField(blank=True, help_text='Date the vacancy ended (usually next lease start date). NULL = currently vacant', null=True)),
                ('days_vacant', models.IntegerField(default=0, help_text='Number of days vacant. Auto-calculated on save.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Currently Vacant'), ('FILLED', 'Filled'), ('EXCLUDED', 'Excluded from Analysis')], default='ACTIVE', help_text='Current status of this vacancy period', max_length=20)),
                ('reason', models.CharField(choices=[('BETWEEN_TENANTS', 'Between Tenants'), ('RENOVATION', 'Renovation/Repairs'), ('SEASONAL', 'Seasonal (Not Marketing)'), ('FIRST_LISTING', 'Initial Property Listing'), ('OWNER_USE', 'Owner/Personal Use'), ('OTHER', 'Other')], default='BETWEEN_TENANTS', help_text='Why is/was this property vacant?', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this vacancy period')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('next_lease', models.ForeignKey(blank=True, help_text='The lease that started after this vacancy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_before', to='pages.tenant')),
                ('previous_lease', models.ForeignKey(blank=True, help_text='The lease that ended before this vacancy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_after', to='pages.tenant')),
                ('prop', models.ForeignKey(help_text='The property that is vacant', on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_periods', to='pages.props')),
            ],
            options={
                'verbose_name': 'Vacancy Period',
                'verbose_name_plural': 'Vacancy Periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['prop', 'status'], name='pages_vacan_prop_id_9f2aef_idx'), models.Index(fields=['start_date', 'end_date'], name='pages_vacan_start_d_b084c1_idx'), models.Index(fields=['status', 'reason'], name='pages_vacan_status_70548f_idx')],
            },
        ),
    ]
