# Generated by Django 5.1.4 on 2025-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_vacancyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='prop_include_in_occupancy',
            field=models.BooleanField(default=True, help_text='Uncheck to exclude this property from occupancy rate and days-to-fill calculations (e.g., for seasonal rentals)', verbose_name='Include in Occupancy Metrics'),
        ),
    ]
