# Generated by Django 5.1.4 on 2026-02-23 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_props_prop_include_in_occupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CelebrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('nameday', 'Nameday'), ('anniversary', 'Anniversary'), ('custom', 'Custom Event')], max_length=20)),
                ('event_date', models.DateField(help_text='The date of the event (month and day)')),
                ('is_recurring', models.BooleanField(default=True, help_text='If checked, event repeats annually')),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_one_week', models.BooleanField(default=True, verbose_name='Notify 1 week before')),
                ('notify_one_day', models.BooleanField(default=True, verbose_name='Notify 1 day before')),
                ('notify_same_day', models.BooleanField(default=True, verbose_name='Notify same day')),
                ('notify_time', models.TimeField(default='09:00:00', help_text='Time to send same-day notification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebration_events', to='pages.contact')),
            ],
            options={
                'verbose_name': 'Celebration Event',
                'verbose_name_plural': 'Celebration Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('one_week', '1 Week Before'), ('one_day', '1 Day Before'), ('same_day', 'Same Day')], max_length=20)),
                ('occurrence_date', models.DateField(help_text='The specific occurrence date this notification is for')),
                ('send_datetime', models.DateTimeField(help_text='When to send this notification')),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pages.celebrationevent')),
            ],
            options={
                'verbose_name': 'Event Notification',
                'verbose_name_plural': 'Event Notifications',
                'ordering': ['send_datetime'],
                'unique_together': {('event', 'notification_type', 'occurrence_date')},
            },
        ),
    ]
