# Generated by Django 5.1.4 on 2026-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_migrate_notification_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrationevent',
            name='notify_alexandra',
            field=models.BooleanField(default=True, help_text='Send notification to Alexandra (leximanias@gmail.com)', verbose_name='Notify Alexandra'),
        ),
        migrations.AddField(
            model_name='celebrationevent',
            name='notify_angy',
            field=models.BooleanField(default=True, help_text='Send notification to Angy (angmaniasbakers@gmail.com)', verbose_name='Notify Angy'),
        ),
        migrations.AddField(
            model_name='celebrationevent',
            name='notify_demetri',
            field=models.BooleanField(default=True, help_text='Send notification to Demetri (demetrimanias@gmail.com)', verbose_name='Notify Demetri'),
        ),
        migrations.AddField(
            model_name='celebrationevent',
            name='notify_erene',
            field=models.BooleanField(default=True, help_text='Send notification to Erene (erenemanias@gmail.com)', verbose_name='Notify Erene'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='cc_addresses',
            field=models.TextField(blank=True, help_text='Comma-separated CC email addresses (optional)'),
        ),
    ]
