# Generated by Django 5.1.4 on 2026-03-13 09:21

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_notificationrecipient_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fa-snowflake')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pages.assetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset Subcategories',
                'db_table': 'asset_subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Supplier',
                'verbose_name_plural': 'Asset Suppliers',
                'db_table': 'asset_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset name/description', max_length=200)),
                ('location_room', models.CharField(help_text='Room/location within property', max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_invoice', models.FileField(blank=True, null=True, upload_to=pages.models.asset_invoice_upload_path)),
                ('brand_manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand/Manufacturer')),
                ('warranty_duration_months', models.IntegerField(blank=True, help_text='Warranty duration in months (will auto-calculate expiry date)', null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, help_text='Warranty expiry date (calculated automatically or entered manually)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.assetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pages.props')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.assetsubcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.assetsupplier')),
            ],
            options={
                'verbose_name': 'Property Asset',
                'verbose_name_plural': 'Property Assets',
                'db_table': 'property_assets',
                'ordering': ['property', 'category', 'subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('replacement', 'Part Replacement'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cost', max_digits=10, null=True)),
                ('service_provider', models.CharField(blank=True, help_text='Technician/company name (optional)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='pages.propertyasset')),
            ],
            options={
                'verbose_name': 'Asset Maintenance Record',
                'verbose_name_plural': 'Asset Maintenance Records',
                'db_table': 'asset_maintenance',
                'ordering': ['-date'],
            },
        ),
    ]
