# Generated by Django 5.1.4 on 2026-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_assetcategory_assetsubcategory_assetsupplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('inspection', 'Inspection'), ('part_replacement', 'Part Replacement'), ('repair', 'Repair'), ('scheduled', 'Scheduled Maintenance'), ('service', 'Service')], max_length=20),
        ),
    ]
