# Generated by Django 5.1.4 on 2026-03-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_alter_assetmaintenance_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyasset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.assetsupplier'),
        ),
    ]
