# Generated by Django 5.1.4 on 2026-03-16 11:58

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_alter_propertyasset_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='invoice',
            field=models.FileField(blank=True, help_text='Optional maintenance invoice or receipt', null=True, upload_to=pages.models.maintenance_invoice_upload_path),
        ),
    ]
