# Generated by Django 5.1.4 on 2026-03-20 05:50

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_assetmaintenance_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_document',
            field=models.FileField(blank=True, help_text='Optional document attachment (PDF, Word, etc.)', null=True, upload_to=pages.models.recipe_document_upload_path, verbose_name='Recipe Document'),
        ),
    ]
