# Generated by Django 5.1.4 on 2026-04-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_recipe_recipe_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_time', models.TimeField(help_text='Default serving time (e.g. 20:00)')),
                ('fire_lighting_duration', models.PositiveIntegerField(help_text='Fire lighting time in minutes')),
                ('resting_duration', models.PositiveIntegerField(help_text='Resting time in minutes')),
                ('cutting_sauce_duration', models.PositiveIntegerField(help_text='Cutting and sauce making time in minutes')),
                ('meat_weight', models.PositiveIntegerField(help_text='Default meat weight in grams')),
                ('rate1_minutes_per_500g', models.DecimalField(decimal_places=1, help_text='Cooking rate for first portion (mins per 500g)', max_digits=5)),
                ('rate1_threshold_grams', models.PositiveIntegerField(blank=True, help_text='Weight at which rate switches to rate2 (e.g. 3000). Leave blank if single rate.', null=True)),
                ('rate2_minutes_per_500g', models.DecimalField(blank=True, decimal_places=1, help_text='Cooking rate for weight above threshold (mins per 500g). Leave blank if single rate.', max_digits=5, null=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_calculation', to='pages.recipe')),
            ],
            options={
                'db_table': 'cooking_calculations',
            },
        ),
    ]
