# Generated by Django 5.1.4 on 2026-04-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_cookingcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingcalculation',
            name='additional_cooking_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Fixed extra cooking time in minutes added regardless of weight (e.g. searing time)', null=True),
        ),
        migrations.AddField(
            model_name='cookingcalculation',
            name='cooking_method',
            field=models.CharField(choices=[('braai', 'Braai / BBQ'), ('oven', 'Oven')], default='braai', help_text='Braai/BBQ or Oven', max_length=10),
        ),
        migrations.AlterField(
            model_name='cookingcalculation',
            name='fire_lighting_duration',
            field=models.PositiveIntegerField(help_text='Fire lighting / oven pre-heating time in minutes'),
        ),
    ]
