# Generated by Django 5.1.4 on 2026-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calories (kcal) per 100g', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carbohydrates (g) per 100g', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fat (g) per 100g', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fdc_data_type',
            field=models.CharField(blank=True, help_text='USDA data type: Foundation, SR Legacy, Survey (FNDDS), or Branded', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fdc_description',
            field=models.CharField(blank=True, help_text='USDA description of the matched food (for reference)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fdc_id',
            field=models.IntegerField(blank=True, help_text='USDA FoodData Central food ID (set when mapped to nutrition data)', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dietary fiber (g) per 100g', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_synced_at',
            field=models.DateTimeField(blank=True, help_text='When nutrition data was last fetched from USDA', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein (g) per 100g', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodium_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sodium (mg) per 100g', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sugars (g) per 100g', max_digits=6, null=True),
        ),
    ]
