# Generated by Django 5.1.4 on 2026-05-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_ingredient_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNutritionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_100g', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calories_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('mapped_count', models.IntegerField(default=0)),
                ('unmapped_count', models.IntegerField(default=0)),
                ('unconvertible_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_cache', to='pages.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Nutrition Cache',
                'verbose_name_plural': 'Recipe Nutrition Caches',
                'db_table': 'recipe_nutrition_cache',
            },
        ),
    ]
