# Generated by Django 5.1.4 on 2026-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_recipenutritioncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_source',
            field=models.CharField(blank=True, choices=[('usda', 'USDA'), ('manual', 'Manual')], help_text='Where the per-100g nutrition values came from. NULL = not set yet.', max_length=10, null=True),
        ),
    ]
