# Generated by Django 5.1.4 on 2026-05-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_ingredient_nutrition_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModificationSuggestion',
            fields=[
                ('recipe_modification_suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('reduce_carbs', 'Reduce carbs'), ('reduce_calories', 'Reduce calories'), ('increase_protein', 'Increase protein'), ('reduce_fat', 'Reduce fat')], max_length=30)),
                ('suggestions_json', models.JSONField(help_text='Validated response from the LLM, matching the schema in recipe_ai.py')),
                ('recipe_version_hash', models.CharField(help_text='SHA256 hash of recipe + ingredient nutrition state at generation time', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_suggestions', to='pages.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Modification Suggestion',
                'verbose_name_plural': 'Recipe Modification Suggestions',
                'db_table': 'recipe_modification_suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipe', 'goal_type'], name='rms_recipe_goal_idx')],
                'unique_together': {('recipe', 'goal_type', 'recipe_version_hash')},
            },
        ),
    ]
