# Generated by Django 5.1.4 on 2026-05-10 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_recipemodificationsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='document_frequency',
            field=models.PositiveIntegerField(default=0, help_text='Number of recipes that use this ingredient. Recomputed by rebuild_recipe_stats.'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='idf',
            field=models.FloatField(default=0.0, help_text='Inverse document frequency: log(N / df). Higher = more distinctive. Recomputed by rebuild_recipe_stats.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weighted_total',
            field=models.FloatField(default=0.0, help_text='Sum of IDF for all ingredients in this recipe. Used as the denominator in WCIM match scoring. Recomputed by rebuild_recipe_stats.'),
        ),
        migrations.CreateModel(
            name='PantryStaple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_having_as_staple', to='pages.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_staples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pantry Staple',
                'verbose_name_plural': 'Pantry Staples',
                'db_table': 'pantry_staples',
                'ordering': ['ingredient__name'],
                'indexes': [models.Index(fields=['user'], name='pantry_stap_user_id_f8c7c9_idx')],
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
