# Generated by Django 5.1.4 on 2026-05-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_ingredient_document_frequency_ingredient_idf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientFamily',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Chicken cuts", "Pork chops", "Beef steaks"', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Notes on what belongs and what does NOT. Critical for safe substitutions.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingredient Family',
                'verbose_name_plural': 'Ingredient Families',
                'db_table': 'ingredient_families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='family',
            field=models.ForeignKey(blank=True, help_text='WCIM equivalence family. Items in the same family are partial substitutes when matching recipes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='pages.ingredientfamily'),
        ),
    ]
