# Generated by Django 5.1.4 on 2026-06-07 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_contact_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to a login account. NULL for members who never sign in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='pages.workspace')),
            ],
            options={
                'verbose_name': 'Household Member',
                'verbose_name_plural': 'Household Members',
                'db_table': 'household_members',
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
