# Generated by Django 5.1.4 on 2026-06-08 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0072_seed_household_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('celebration_reminder', 'Celebration Reminders'), ('document_expiry', 'Document Expiry Alerts')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pages.householdmember')),
            ],
            options={
                'verbose_name': 'Member Notification Subscription',
                'verbose_name_plural': 'Member Notification Subscriptions',
                'db_table': 'member_notification_subscriptions',
                'ordering': ['member__name', 'notification_type'],
                'unique_together': {('member', 'notification_type')},
            },
        ),
    ]
