# Generated by Django 5.1.4 on 2026-06-08 03:36
from django.db import migrations

PERSONAL_TYPES = ['celebration_reminder', 'document_expiry']


def _csv_set(value):
    return {e.strip().lower() for e in (value or '').split(',') if e.strip()}


def backfill(apps, schema_editor):
    HouseholdMember = apps.get_model('pages', 'HouseholdMember')
    NotificationRecipient = apps.get_model('pages', 'NotificationRecipient')
    Subscription = apps.get_model('pages', 'MemberNotificationSubscription')

    for rec in NotificationRecipient.objects.filter(
        notification_type__in=PERSONAL_TYPES, workspace__isnull=False
    ):
        emails = _csv_set(rec.to_addresses) | _csv_set(rec.cc_addresses)
        if not emails:
            continue
        for m in HouseholdMember.objects.filter(workspace=rec.workspace):
            if m.email and m.email.strip().lower() in emails:
                Subscription.objects.get_or_create(
                    member=m,
                    notification_type=rec.notification_type,
                    defaults={'is_active': True},
                )


def unbackfill(apps, schema_editor):
    Subscription = apps.get_model('pages', 'MemberNotificationSubscription')
    Subscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0073_membernotificationsubscription'),
    ]

    operations = [
        migrations.RunPython(backfill, reverse_code=unbackfill),
    ]