# Generated by Django 5.1.4 on 2026-06-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0074_backfill_member_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrationevent',
            name='relevant_to',
            field=models.ManyToManyField(blank=True, help_text='Household members this event pertains to (the relevance axis).', related_name='relevant_events', to='pages.householdmember'),
        ),
    ]
