# Generated by Django 5.1.4 on 2026-06-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0076_backfill_event_relevance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrationevent',
            name='notify_alexandra',
        ),
        migrations.RemoveField(
            model_name='celebrationevent',
            name='notify_angy',
        ),
        migrations.RemoveField(
            model_name='celebrationevent',
            name='notify_demetri',
        ),
        migrations.RemoveField(
            model_name='celebrationevent',
            name='notify_erene',
        ),
    ]
