# Generated by Django 5.1.4 on 2026-06-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0077_remove_celebrationevent_notify_alexandra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_bill_levies',
            field=models.BooleanField(default=False, help_text="Include tenant_levies as a communal line — on the physical invoice and in the collection amount. Off = today's rent-only behaviour.", verbose_name='Bill Communal Fees (Levies)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_physical_invoice_required',
            field=models.BooleanField(default=False, help_text='Also generate and email a PDF VAT invoice for this tenant each month.', verbose_name='Generate Physical Invoice'),
        ),
        migrations.CreateModel(
            name='PhysicalInvoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id_label', models.CharField(blank=True, help_text="Shown in the 'Customer ID' box. Defaults to the tenant name if blank.", max_length=255)),
                ('billing_name', models.CharField(blank=True, help_text='Customer name on the invoice. Defaults to the tenant name if blank.', max_length=255)),
                ('billing_address', models.TextField(blank=True, help_text='Customer address — one line per row.')),
                ('billing_tel', models.CharField(blank=True, help_text='Defaults to the tenant contact number if blank.', max_length=64)),
                ('water_enabled', models.BooleanField(default=False, help_text='Prompt for a (VAT-free) Water Consumed line on the scheduled months.')),
                ('water_cycle_anchor', models.DateField(blank=True, help_text="Any month this tenant's water cycle lands on; the interval counts from here.", null=True)),
                ('water_cycle_interval_months', models.PositiveSmallIntegerField(default=2, help_text='Months between water lines (2 = every second month).')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_invoice_profile', to='pages.tenant')),
            ],
            options={
                'verbose_name': 'Physical Invoice Profile',
                'verbose_name_plural': 'Physical Invoice Profiles',
                'db_table': 'physical_invoice_profile',
            },
        ),
    ]
