# Generated by Django 5.1.4 on 2026-06-23 03:18

import django.db.models.deletion
import pages.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0078_tenant_tenant_bill_levies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInvoice',
            fields=[
                ('physical_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('invoice_date', models.DateField(help_text='Printed on the invoice (1st of the period month).')),
                ('invoice_number', models.CharField(blank=True, help_text='PR-#### — assigned when the invoice is sent.', max_length=32, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1900'), help_text='VAT rate applied to vatable lines, frozen on this invoice.', max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=pages.models.physical_invoice_pdf_upload_path)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_physical_invoices', to=settings.AUTH_USER_MODEL)),
                ('collection_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_invoice', to='pages.invoices')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_invoices', to='pages.tenant')),
            ],
            options={
                'verbose_name': 'Physical Invoice',
                'verbose_name_plural': 'Physical Invoices',
                'db_table': 'physical_invoices',
                'ordering': ['-period_year', '-period_month', 'tenant_id'],
                'unique_together': {('tenant', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalInvoiceLine',
            fields=[
                ('physical_invoice_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vatable', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('physical_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pages.physicalinvoice')),
            ],
            options={
                'verbose_name': 'Physical Invoice Line',
                'verbose_name_plural': 'Physical Invoice Lines',
                'db_table': 'physical_invoice_lines',
                'ordering': ['sort_order', 'physical_invoice_line_id'],
            },
        ),
    ]
