# Generated by Django 5.1.4 on 2026-06-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0079_physicalinvoice_physicalinvoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInvoiceNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='PR-', max_length=10)),
                ('pad_width', models.PositiveSmallIntegerField(default=4, help_text='Zero-padding width (4 -> PR-0170).')),
                ('next_number', models.PositiveIntegerField(default=1, help_text='The next PR number the system will issue.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Physical Invoice Numbering',
                'verbose_name_plural': 'Physical Invoice Numbering',
                'db_table': 'physical_invoice_numbering',
            },
        ),
    ]
