# Generated by Django 5.1.4 on 2026-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0082_alter_notificationrecipient_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalinvoiceprofile',
            name='client_email_body',
            field=models.TextField(blank=True, help_text="Saved greeting and body for the monthly invoice e-mail. Use {month} where the period should appear; the send cron replaces it with the month and year (e.g. 'June 2026'). Leave blank to use a generic default."),
        ),
    ]
