# Generated by Django 5.1.4 on 2026-07-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0084_invoice_customer_and_customer_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Model field that changed, e.g. 'issues_heading', 'issues_description', 'prop'.", max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, help_text='Set when the change was to a comment rather than an issue field; NULL for issue-field changes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='pages.issues_details')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='pages.issues')),
                ('user', models.ForeignKey(blank=True, help_text='Who made the change. NULL if the account was later removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Audit Log Entry',
                'verbose_name_plural': 'Issue Audit Log',
                'db_table': 'issue_audit_log',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
