# Generated by Django 5.1.4 on 2026-07-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0085_issueauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFigureHistory',
            fields=[
                ('financial_figure_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('revenue', 'Revenue (direct / seasonal)'), ('budget_expense', 'Budgeted expense')], max_length=20)),
                ('source_pk', models.IntegerField(help_text='expense_id or revenue_id of the source row')),
                ('line_type', models.CharField(blank=True, help_text='Denormalised line-type label, e.g. Rental / Insurance.', max_length=255, null=True)),
                ('effective_date', models.DateField(help_text='Date from which these values apply.')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base amount at this version (mirrors expense_amount / revenue_amount).', max_digits=10, null=True)),
                ('jan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('may', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jun', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nov', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, help_text='budget | direct | prorata | prorata_line | prorata_valuation | seed', max_length=30, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_history', to='pages.props')),
            ],
            options={
                'verbose_name': 'Financial Figure History',
                'verbose_name_plural': 'Financial Figure History',
                'db_table': 'financial_figure_history',
                'ordering': ['prop_id', 'kind', '-effective_date', '-changed_at'],
                'indexes': [models.Index(fields=['prop', 'kind', 'effective_date'], name='financial_f_prop_id_e2351a_idx'), models.Index(fields=['kind', 'source_pk'], name='financial_f_kind_f31395_idx')],
            },
        ),
    ]
