# Generated by Django 5.1.4 on 2026-08-28 08:52

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0091_notification_label_invoice_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceiptNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='CR-', max_length=10)),
                ('pad_width', models.PositiveSmallIntegerField(default=5, help_text='Zero-padding width (5 -> CR-00372).')),
                ('next_number', models.PositiveIntegerField(default=372, help_text='The next CR number the system will issue.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Receipt Numbering',
                'verbose_name_plural': 'Cash Receipt Numbering',
                'db_table': 'cash_receipt_numbering',
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('cash_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='CR-##### — assigned when the receipt is issued.', max_length=32, unique=True)),
                ('receipt_date', models.DateField(help_text='The date the money was received.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.TextField(help_text='What the payment was for.')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='transfer', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Optional — e.g. the invoice this settles. May be left blank.', max_length=64)),
                ('doc_format', models.CharField(choices=[('electronic', 'Electronic'), ('printed', 'Printed')], default='electronic', help_text='Electronic omits the signature block and states the receipt is valid without one. Printed carries the ruled lines instead. Chosen once, at issue.', max_length=20)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_address', models.TextField(blank=True, help_text='One line per row. Optional — a receipt is valid without it.')),
                ('payer_tel', models.CharField(blank=True, max_length=64)),
                ('payer_email', models.TextField(blank=True, help_text='Comma-separated addresses used when the receipt is emailed.')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=pages.models.cash_receipt_pdf_upload_path)),
                ('is_void', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cash_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='pages.invoicecustomer')),
                ('prop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='pages.props')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='pages.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_cash_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Receipt',
                'verbose_name_plural': 'Cash Receipts',
                'db_table': 'cash_receipts',
                'ordering': ['-receipt_date', '-cash_receipt_id'],
            },
        ),
    ]
