# Generated by Django 5.1.4 on 2026-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text="ISO 3166-1 alpha-2 country code, e.g. 'CY' for Cyprus.", max_length=2, unique=True)),
                ('country_name', models.CharField(help_text="Human-readable country name, e.g. 'Cyprus'.", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive configurations cannot be used for new submissions.')),
                ('oecd_version', models.CharField(default='2.0', help_text='OECD CRS XML schema version for submissions to this country.', max_length=10)),
                ('tin_regex', models.CharField(blank=True, default='', help_text='Regex for validating TINs issued by this country. Optional.', max_length=500)),
                ('message_ref_id_template', models.CharField(default='[SENDING_FI_IN].[YEAR]_[UUID]', help_text='Template for MessageRefID. Tokens resolved at submission time.', max_length=200)),
                ('fi_doc_ref_id_template', models.CharField(default='[SENDING_FI_IN].[YEAR]_[YYYYMMDDHHMM]_[UUID]', help_text='Template for ReportingFI DocRefID.', max_length=200)),
                ('account_doc_ref_id_template', models.CharField(default='[SENDING_FI_IN].[YEAR]_[YYYYMMDDHHMM]_[UUID]', help_text='Template for each AccountReport DocRefID.', max_length=200)),
                ('output_filename_template', models.CharField(default='[SENDING_FI_IN]_[CURRENT_DATE].xml', help_text='Template for the generated XML filename.', max_length=200)),
                ('default_currency', models.CharField(default='EUR', help_text='Default currency for new submissions (ISO 4217 alpha-3).', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Configuration',
                'verbose_name_plural': 'Country Configurations',
                'ordering': ['country_code'],
            },
        ),
    ]
