# Generated by Django 5.1.4 on 2026-05-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0002_seed_cyprus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal name of the FI (OECD Name element; max 200 chars).', max_length=200)),
                ('name_type', models.CharField(choices=[('legal', 'Legal Name'), ('dba', 'Doing Business As'), ('alias', 'Alias'), ('aka', 'Also Known As')], default='legal', help_text="OECD nameType qualifier. Defaults to 'legal' for FIs.", max_length=20)),
                ('res_country_code', models.CharField(help_text='ResCountryCode — ISO 3166-1 alpha-2 tax residence of the FI.', max_length=2)),
                ('address_country_code', models.CharField(help_text='Address CountryCode — ISO 3166-1 alpha-2 (Validation per spec).', max_length=2)),
                ('address_free', models.TextField(help_text='Free-text address string (OECD AddressFree element; up to 4000 chars).')),
                ('address_type', models.CharField(choices=[('residentialOrBusiness', 'Residential or Business'), ('residential', 'Residential'), ('business', 'Business'), ('registeredOffice', 'Registered Office'), ('unspecified', 'Unspecified')], default='registeredOffice', help_text="OECD legalAddressType qualifier. Defaults to 'registeredOffice' for FIs.", max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive FIs cannot be selected for new submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporting Financial Institution',
                'verbose_name_plural': 'Reporting Financial Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingFIIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_value', models.CharField(help_text='The identification number itself (max 200 chars per spec).', max_length=200)),
                ('issued_by', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code of the issuing jurisdiction. Optional.', max_length=2)),
                ('in_type', models.CharField(blank=True, choices=[('TIN', 'TIN — Tax Identification Number'), ('GIIN', 'GIIN — Global Intermediary Identification Number'), ('EIN', 'EIN — Employer Identification Number'), ('BRN', 'BRN — Business Registration Number'), ('LEI', 'LEI — Legal Entity Identifier'), ('Other', 'Other')], default='', help_text='Type of identification number. Optional.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fi', models.ForeignKey(help_text='The ReportingFI this IN belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ins', to='crs.reportingfi')),
            ],
            options={
                'verbose_name': 'Reporting FI Identification Number',
                'verbose_name_plural': 'Reporting FI Identification Numbers',
                'ordering': ['in_type', 'in_value'],
                'unique_together': {('fi', 'in_value')},
            },
        ),
    ]
