# Generated by Django 5.1.4 on 2026-05-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0003_reportingfi_reportingfiin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='contact',
            field=models.TextField(blank=True, default='', help_text="Free-text contact details for the person at the FI handling CRS submissions (name, email, phone). Used to populate the Message Header's Contact element at XML generation time. Optional per spec."),
        ),
    ]
