# Generated by Django 5.1.4 on 2026-05-21 03:28

import crs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0004_reportingfi_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Reporting year (e.g. 2025). ReportingPeriod is computed as Dec 31 of this year.')),
                ('sending_company_in', models.CharField(help_text="Snapshot of the FI IN used as SendingCompanyIN in the Message Header. Frozen at draft creation; not updated if the FI's INs change later.", max_length=200)),
                ('transmitting_country', models.CharField(help_text="TransmittingCountry — ISO 3166-1 alpha-2. Defaults to the FI's residence country at draft creation.", max_length=2)),
                ('receiving_country', models.CharField(help_text='ReceivingCountry — ISO 3166-1 alpha-2. For domestic reporting (Cyprus FI → Cyprus tax authority), same as TransmittingCountry.', max_length=2)),
                ('document_type', models.CharField(choices=[('OECD0', 'OECD0 — Resent Data'), ('OECD1', 'OECD1 — New Data'), ('OECD2', 'OECD2 — Corrected Data'), ('OECD3', 'OECD3 — Deletion of Data')], default='OECD1', help_text='DocSpec DocTypeIndic. MVP uses OECD1 (new data).', max_length=10)),
                ('message_type', models.CharField(choices=[('CRS701', 'CRS701 — New Information'), ('CRS702', 'CRS702 — Corrections / Deletions'), ('CRS703', 'CRS703 — Nil Reporting')], default='CRS701', help_text='MessageTypeIndic. MVP uses CRS701 (new information).', max_length=10)),
                ('message_ref_id', models.CharField(help_text="MessageRefID — minted from the country config's template at draft creation, immutable thereafter. Must be unique in time and space per OECD spec.", max_length=170, unique=True)),
                ('corr_message_ref_id', models.CharField(blank=True, default='', help_text='CorrMessageRefID — only used for CRS702 correction messages. Empty for MVP (CRS701 only).', max_length=170)),
                ('warning', models.TextField(blank=True, default='', help_text='Optional free-text Warning element on the Message Header.')),
                ('uploaded_excel', models.FileField(blank=True, help_text='Transient — uploaded customer data Excel. Deleted on submission closure.', null=True, upload_to=crs.models.excel_upload_path)),
                ('generated_xml', models.FileField(blank=True, help_text='Durable — generated CRS XML. Survives submission closure.', null=True, upload_to=crs.models.xml_output_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('submitted_externally', 'Submitted Externally'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected')], default='draft', help_text='Current lifecycle state.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xml_generated_at', models.DateTimeField(blank=True, help_text='Set when XML is built; also used as the Message Header Timestamp value in the XML.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when the user closes the submission (temp data purged).', null=True)),
                ('submitted_externally_at', models.DateTimeField(blank=True, help_text='User-stamped after filing the XML with the tax authority.', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='User-stamped after receiving acknowledgement/rejection.', null=True)),
                ('acknowledgement_notes', models.TextField(blank=True, default='', help_text='Notes captured after external submission (receipt details, rejection reasons, reference numbers).')),
                ('country_config', models.ForeignKey(help_text='The country whose reporting rules and templates apply.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='crs.countryconfiguration')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_submissions', to=settings.AUTH_USER_MODEL)),
                ('reporting_fi', models.ForeignKey(help_text='The FI on whose behalf this submission is filed.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='crs.reportingfi')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
