# Generated by Django 5.1.4 on 2026-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0005_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryconfiguration',
            name='receiving_country_strategy',
            field=models.CharField(choices=[('combined_domestic', 'Combined Domestic File'), ('split_by_residence', 'Split by Residence')], default='combined_domestic', help_text="How XML files are generated for this country. 'Combined Domestic File' produces one XML with ReceivingCountry = TransmittingCountry (the FI's country) and lets the tax authority handle bilateral split downstream. 'Split by Residence' produces one XML per receiving country, each containing only accounts whose holders are tax-resident in that country.", max_length=20),
        ),
    ]
