# Generated by Django 5.1.4 on 2026-05-21 16:09

import crs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0006_countryconfiguration_receiving_country_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='generated_xml',
        ),
        migrations.CreateModel(
            name='SubmissionXMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_country', models.CharField(help_text="ReceivingCountry ISO 3166-1 alpha-2 in this file's MessageSpec.", max_length=2)),
                ('file', models.FileField(upload_to=crs.models.xml_file_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes at generation time.')),
                ('account_count', models.PositiveIntegerField(help_text='Number of <AccountReport> elements in this file.')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_files', to='crs.submission')),
            ],
            options={
                'verbose_name': 'Submission XML file',
                'verbose_name_plural': 'Submission XML files',
                'ordering': ['receiving_country'],
                'unique_together': {('submission', 'receiving_country')},
            },
        ),
    ]
