# Generated by Django 5.1.4 on 2026-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0007_remove_submission_generated_xml_submissionxmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_nil_return',
            field=models.BooleanField(default=False, help_text="When True, this is a CRS703 nil return: the FI has carried out its due-diligence checks and has no reportable accounts. No Excel upload is required; a single empty-ReportingGroup XML file is generated for the FI's own jurisdiction."),
        ),
    ]
